### ISSUE TITLE
Distinct fields not supported by DB backend used by tests

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#1003]
In conjunction to solving issue #993 , the proposed fix triggered an error in deadline deviations unit tests:
"django.db.utils.NotSupportedError: DISTINCT ON fields is not supported by this database backend"

Django default DB is sqlite3, which is used in tests. Apparently, based on this error message, it does not support DISTINCT. We should consider changing the DB backend in tests to something else, that is more compatible with the current use in production (postgresql)

**Comment by Mankro** [comment]
The `distinct()` method works without parameters on all database management systems. The `fields` argument is specific to PostgreSQL.

https://docs.djangoproject.com/en/3.2/ref/models/querysets/#distinct

**Comment by PasiSa** [comment]
Acknowledged.
