### ISSUE TITLE
API endpoint for regrading submissions

### ISSUE THREAD

**Issue by jaakkonarhi** [apluslms/a-plus#1008]
Like the one in the inspect view https://plus.cs.aalto.fi/o1/2022/w01/ch02/w01_ch02_2/submissions/4936438/inspect/ 

https://plus.cs.aalto.fi/o1/2022/w01/ch02/w01_ch02_2/submissions/4936438/re-submit/

This feature would be used in the A+ Courses IntelliJ plugin and it would be shown only for course assistants. [Here's the relevant PR.](https://github.com/Aalto-LeTech/aplus-courses/pull/851) It would be useful when developing tests for a course, so you don't need to keep making new submissions to try the new tests.

**Comment by annirytkonen** [comment]
could you please specify the schedule for the need so we can better schedule the task in the sprints.

**Comment by jaakkonarhi** [comment]
I would like to have it pretty soon, preferably in the next few releases

**Comment by annirytkonen** [comment]
ok; note our next release schedules https://wiki.aalto.fi/display/EDIT/Aplus+spring+2022 and https://wiki.aalto.fi/display/EDIT/Aplus+summer+and+autumn+2022
