### ISSUE TITLE
To be tested and documented: visualization assignment points

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#1017]
1) Test: Tehtävien teossa (visualisointitehtävä): pisteeni eivät tallentuneet
2) document the test results a) below in a comment, if not repeatable, or b) in a new issue on fixing this
3) close this issue

**Comment by Mankro** [comment]
At least in JSAV exercises, we know that it is possible to lose the points. When the student completes the JSAV exercise, the JS code is supposed to send an HTTP POST request to the grader for storing the submission and points. If the request fails, the server crashes or the grader can't deliver the results to A+ front, then the points and the whole submission is lost. In the case of AJAX-based exercises like JSAV, A+ does not even store any submission if delivering the points fails. There is no sign that the student has attempted or completed the exercise, which is particularly cumbersome during exams.
