### ISSUE TITLE
Remove sign in as another user

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#1032]
It shouldn't be possible to log in as another user in a production system. Remove the old code for the SignInAsUser view completely.

* https://github.com/apluslms/a-plus/blob/e832ba304b22392e8acc0e47292a4ccd3dae24b0/edit_course/views.py#L396-L413
* https://github.com/apluslms/a-plus/blob/e832ba304b22392e8acc0e47292a4ccd3dae24b0/edit_course/urls.py#L46-L48

**Comment by annirytkonen** [comment]
ok!

**Comment by oseppala** [comment]
It's mostly just reverting this:
https://github.com/apluslms/a-plus/commit/4e2bc94c1006b7a65b89bbc30a94457dd4baab35

There are just a few lines that are used for another purpose in that commit
