### ISSUE TITLE
Identical/duplicate submission warning should not be shown in git repo submissions

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#1076]
#1048 added a warning when the student makes an identical submission to a previous one. However, in assignments that take submissions as git repos, the submission is always expected to be the same git URL. The identical submission warning should not be shown in git repo submissions.

Git repo assignments use the MOOC-Grader `view_type` `access.types.stdasync.acceptGitAddress`.
C++ 2022 course is one example of a course that uses git repo submissions.

![image](https://user-images.githubusercontent.com/6130378/189321963-383a46c4-1b66-42f6-a3ab-f53af107dfc9.png)

**Comment by jykesaviaGNH** [comment]
I believe that Tampere teachers have similar submissions, which are not neccessary of type `acceptGitAddress`. Perhaps there should be an option to disable the duplicate check?
