### ISSUE TITLE
Exercise list API /api/v2/courses/<course_id>/exercises/ should use caching to boost performance

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#1084]
This course exercise list API endpoint seems to be too heavy for the database during the busy periods with heavy traffic (e.g., many students working right before course deadlines). 
https://github.com/apluslms/a-plus/blob/a236226539c7a37f601e78a3bb39ec9f76c843fa/course/api/views.py#L178-L211

It does not currently use the cache at all. Try to use the cache so that it would not always query all the course modules and assignments from the database.

`CourseExerciseTreeViewSet` already uses the cache through the `self.content` variable. This API endpoint has been clearly faster.
https://github.com/apluslms/a-plus/blob/a236226539c7a37f601e78a3bb39ec9f76c843fa/course/api/views.py#L214-L241

`self.content` is inherited from `CourseInstanceBaseMixin`:
https://github.com/apluslms/a-plus/blob/a236226539c7a37f601e78a3bb39ec9f76c843fa/course/viewbase.py#L61
It uses `CachedContent`: https://github.com/apluslms/a-plus/blob/a236226539c7a37f601e78a3bb39ec9f76c843fa/exercise/cache/content.py#L14

**Comment by Mankro** [comment]
Django and REST framework also offer view specific caching with a very simple annotation in the code, but I assume it would cache this specific view for each course separately (each different URL with the course id). Since we already have similar data in the cache under `CachedContent`, using the annotations would just duplicate a lot of data in the cache. That doesn't sound optimal at all.

https://www.django-rest-framework.org/api-guide/caching/

**Comment by EerikSaksi** [comment]
Anyone assigned on this?

**Comment by Mankro** [comment]
> Anyone assigned on this?

You can start it!
