### ISSUE TITLE
Quick team selection in Edit Submitters view selects wrong students

### ISSUE THREAD

**Issue by oseppala** [apluslms/a-plus#1091]
The edit submitters view has a functionality that allows selecting team members quickly from a list.

Picking any team from the list however does not select the students that are shown next to the list.

To reproduce, try to modify any submission and select any group from the list. The students that appear in the form are not the ones in the selected group.

**Comment by Mankro** [comment]
I looked into this.
The "select group" button queries the user data from the backend API. The URL parameters contain the User.id values of the users whose names are displayed in the table row, but the API returns different users whose UserProfile.id values match the query parameters. User.id does not equal UserProfile.id in the production database.
