### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [apluslms/a-plus#1097]
Hi, In **a-plus**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
beautifulsoup4~=4.9.3
Django~=3.2.4
django-bootstrap-form~=3.4
django-html5-colorfield==1.0
django-settingsdict~=1.1.1
djangorestframework~=3.13.1
djangorestframework-csv~=2.1.0
git+https://github.com/apluslms/drf-extensions.@reimplement_nested_routes_v6+https://github.com/apluslms/django-essentials.@1.5.0+https://github.com/apluslms/js-jquery-toggle.@1.1.0+https://github.com/apluslms/django-colortag.@2.3.0
feedparser~=6.0.2
html5lib~=1.1
lxml>=4.6.3<5
cachetools~=4.2.1
icalendar~=4.0.7
oauthlib~=3.1.0
Pillow>=9.0.0
python-dateutil~=2.8.1
social-auth-app-django>=4.0.0<5
social-auth-core>=4.1.0<5
pytz>=2021.1
reportlab>=3.5.0<4
requests>=2.25.1<3
unittest-xml-reporting>=3.0.4<4
markdown~=3.3.4
aplus-auth~=0.2.0
celery>=5.2.1<6
redis>=4
binaryornot~=0.4.4
django-model-utils~=4.2.0
format_cef~=0.0.4
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **Pillow** can be changed to *==9.2.0*.
The version constraint of dependency **Pillow** can be changed to *>=2.0.0,<=9.1.1*.
The version constraint of dependency **python-dateutil** can be changed to *>=2.1,<=2.8.2*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the Pillow</summary>
 <pre>PIL.Image.open
</pre>
</details>
<details><summary>The calling methods from the python-dateutil</summary>
 <pre>dateutil.relativedelta.relativedelta
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by Mankro** [comment]
Thanks, but your suggestions do not look useful to me. The different Pillow version ranges that you presented even conflict with each other. 

Closing. Assuming that you are a bot, we don't need your services.
