### ISSUE TITLE
It should be possible to control chapter visibility in the same way as model solution visibility in assignments

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#1098]
Especially the O1 course (Programming 1, @jsorva) regularly uses chapters at the start of modules that provide feedback and commentary on the previous module and its assignments. In practice, the chapter also reveals model solutions for some of the assignments in the past module. The normal deadline of the past module has passed at this point, but there are always students who have personal deadline extensions. It should be possible to set full chapters as model solutions whose visibility can be controlled with the same settings that are available to assignment model solutions. Assignments already support flexible settings for the visibility of model solutions.

Assignment model solutions currently use the `BaseExercise.model_solutions_reveal_rule` field to control their visibility.
https://github.com/apluslms/a-plus/blob/34cc48150212b0ff9ebd55c7c47e97f21b07f706/exercise/exercise_models.py#L520

Reveal rule and exercise reveal state classes:
* https://github.com/apluslms/a-plus/blob/34cc48150212b0ff9ebd55c7c47e97f21b07f706/exercise/reveal_models.py#L12
* https://github.com/apluslms/a-plus/blob/34cc48150212b0ff9ebd55c7c47e97f21b07f706/exercise/reveal_states.py#L35

User docs for the existing reveal rules in the A-plus-rst-tools README:
https://github.com/apluslms/a-plus-rst-tools/blob/40c904b69e16518bf8e01cffac70877b58bbc448/README.md#defining-reveal-rules

**Comment by jsorva** [comment]
Big thumbs up to this issue! Implementing this would pre-empt significant opportunities for cheating / bad study habits.

**Comment by Mankro** [comment]
> Tietyt materiaalin sivut pitäisi voida merkitä osaksi tietyn kierroksen ratkaisuja eli ne tulisivat näkyviin opiskelijalle vain jos hänen henk.koht. deadlinensa tuolle kierrokselle on mennyt. (Esim. O1:n viikkokoosteet.)
>
> Olisi erittäin hyödyllistä, jos voisi myös määritellä, että tietty vaihtoehtoinen sisältö tuolla sivulla näkyy sellaisille opiskelijoille, joiden kohdalla deadline ei ole vielä mennyt

From Juha's GDoc. The second part wasn't included in the first post in this issue. In English:

It would be useful if the "model solution chapter" could show alternative contents to those whose deadline has not passed (and thus they do not see the actual model solutions). This implies that the chapter page itself would always be visible, but the contents would vary based on the model solution visibility setting.


----------------------

Note that chapter's already include the "audience" setting that can restrict the whole chapter to only internal, external or any logged-in enrolled student (or to anyone who can see the course based on the `CourseInstance.view_content_to` setting).
https://github.com/apluslms/a-plus/blob/34cc48150212b0ff9ebd55c7c47e97f21b07f706/exercise/exercise_models.py#L108

**Comment by oseppala** [comment]
Upvote! We have problems with students submitting model solutions they copy from chapters that should not be seen while they still solve exercises.

**Comment by jsorva** [comment]
It would be a nice bonus if students could see teacher-configured custom content in place of the standard module that is currently hidden from them. For example, the teacher could configure (in RST) some module-specific content that is displayed in place of a weekly bulletin to those students who don’t yet have access to the bulletin. 

This would be somewhat useful irrespective of whether bulletin visibility can be personalized, but especially useful if it can. (However, this is still just a "bonus idea", and the important thing would be to support personalized visibility adjustments in the first place, as suggested in this issue.)
