### ISSUE TITLE
Counter for manually assessed students in the submitters list view

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/a-plus#1109]
In the assignment submitters list/table, there is a column "Assessed manually Yes/No". **Add a counter (to the top) that shows how many students have been manually assessed thus far.** For example, "5 students out of 20 have been manually assessed thus far" or in a compact form, "5 / 20 (25%)". 

How to find the assignment submitters table? When you open the submissions list of an assignment, there is a button "Group by submitter" in the top.

Where exactly should the counter be rendered? Ideas:

* Above the table
* In the table column header cell that contains the text "Assessed manually"
* In the inspect submission view since the manual assessment is conducted there in practice.
* elsewhere?

The counter is useful when assignments are manually assessed, for example, in exams.

**Comment by Mankro** [comment]
The counter could also be added to the **inspect submission view**. It would then easily reveal how many students are still left "in the queue" while the course staff are working on the assessments.

(The inspect submission view contains the manual assessment form.)

**Comment by Mankro** [comment]
I think we would like to see the counter in the following locations:
* inspect submission page
* submitters list for an assignment
* all submissions list for an assignment (the counter still counts the submitters, not individual submissions)

Think of a good location within the pages where to put the counter.
