### ISSUE TITLE
Separate vertical scroll bars for the submitted file and the grader feedback in the inspect submission view

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#1111]
The inspect submission view shows submitted files on the left and the grader feedback on the right. When the contents are long, **it would be useful to scroll both sides independently vertically**, that is to say, you could scroll down the submitted file without scrolling/moving the grader feedback part.

This is useful in manual assessment, e.g., in the Y1 course exam.

**Comment by EerikSaksi** [comment]
I added a commit which makes HTML grader results scrollable, and ensures that if there's multiple submitted files each with their own "Scroll Separately" button that they are synced.
