### ISSUE TITLE
Bypass (or improve) the slow-loading DL deviations page

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1122]
For me, loading O1 2022’s "List deadline deviations" page takes about 105 seconds: 65 before anything visible happens and another 40 before the page has fully loaded. It’s not a nice page to navigate to, but (at least in principle) one has to do that pretty often in order to access "Add deadline deviations". 

The ideal fix would be to improve loading times a lot. Failing that (or even if load times are improved), it would be nice to have a faster route to adding deviations; there’s generally no need to browse the current list first.

-------------------------------------------------------------------------

Another issue #1302 focuses on improving the performance of the deviations list view.

**Comment by jsorva** [comment]
I realize it’s possible to use bookmarks and custom A+ menu items to circumvent this.

**Comment by Mankro** [comment]
We already tried to improve the loading times in the past. The loading times did improve, but they can still be too slow. In this issue, we could simply add the requested shortcut links that help the teacher avoid the slow-loading deviation list page.

In the left-side course menu, we could add a subheading "Deviations" and move all the deviation links under that section. We already have two menu links for the deadline and submission attempt deviation lists. We could add two new links that point directly to the "add deviation" forms.

HTML template for the course menu:
https://github.com/apluslms/a-plus/blob/7f21d5ad5b20d7dc4d02c2bb7601720527d07c77/course/templates/course/_course_menu.html#L190-L200

**Comment by lainets** [comment]
The links on the points page in #1123 can trivially be also added to the course page as well. Would that solve the issue or would it clutter the UI too much?

**Comment by Mankro** [comment]
> The links on the points page in #1123 can trivially be also added to the course page as well. Would that solve the issue or would it clutter the UI too much?

@lainets I don't understand your question. This issue #1122 and #1123 are related to different parts of the user interface. Both are useful.

**Comment by lainets** [comment]
As far as I understand, this issue is about improving or bypassing the list deadline deviations page and the exact location of the button(s) for bypassing it hasn't been specified. My question was whether it would be enough to add buttons to the main course page, just like #1123 adds them to the points page. The points page and main course page use the same template (except if the mode is changed by the course but the buttons can be added to the other templates as well), so adding the buttons to the course page as well is trivial (in fact, I had to specifically omit them from the course page in the proposed solution to #1123).

**Comment by Mankro** [comment]
@jsorva should comment on that. 

1. Do we need assignment-specific shortcut links to the "add deviations" form in the course front page and/or "Your points" page? (There is no student pre-selected in these cases.)

2. Do we also need shortcut links to the "add deviations" form in the left-side course menu (navigation panel)? (No assignments nor students pre-selected in this case.)

**Comment by Mankro** [comment]
Based on jsorva's comment, #1123 is important and then this issue #1122 becomes unnecessary.

**Comment by jsorva** [comment]
@Mankro I would consider reopening this issue. 

It’s true that #1123 bypasses the main problem, which is great.

However, parts of the problem remain:
* The deviations list page still loads extremely slowly and more often than not crashes with a server error. (The list is not needed often, but when it is, it’s painful to try to access it.)
* When adding a deadline deviation, one is automatically taken to the deviations list. This basically renders one’s browser tab unusable (for the above reason).
* When adding a deadline deviation, one is automatically taken to the deviations list. Given the poor performance of that page, this unnecessarily strains the server (I presume). Moreover, it strains the server at a bad time (since deadline deviations are typically added near the deadline, when the server is busy).

**Comment by Mankro** [comment]
I made a new issue #1302 that focuses on performance issues in the deviations list. This issue #1122 can focus on bypassing the list view.

**Comment by Mikael-Lenander** [comment]
> OK, we can re-open this issue and consider adding new shortcut links as has been previously discussed in this issue. Though, your concerns are really about the slow performance of the deviation list page and that is a different problem than adding shortcut links.
> 
> There could also be a new "deviations home page" that does not list any deviations from the database, but includes links to the deviation features like adding new. This home page would be a sensible redirect location after adding new deviations if we want to not redirect to the list view. Otherwise, the home page would be rather pointless so it's not the greatest of ideas. Maybe the user could be redirected to the "add new deviation" form again after submitting the same form.
> 
> One approach to the deviation list performance problem is to use pagination so that only 100 records are loaded per page. Then, a search feature would be needed to find students without browsing through all the deviation list pages.

How would the pagination be implemented? Currently, the deviation list groups deviations if the belong to the same module and have the same amount of extra time or same number of extra submissions. If only 100 records per page would be fetched, some records belonging to a group would probably be fetched and some would not. Then the group cannot be formed because all the group members are not fetched.
