### ISSUE TITLE
Link from points pages to "Add deadline deviations" 

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1123]
A common scenario: a teacher is discussing a possible DL extension with a student, looks up the student’s points page in order to check it, then proceeds to extend the deadline. Currently, this involves going through the separate "Add deadline deviations" function, looking up the student again via that form, and then extending the deadline. 

It would be a nice little quality-of-life improvement if there was a link from each student’s points page to the Add deadline deviations function, such that the student would be auto-filled into the form.

**Comment by lainets** [comment]
Would you want a separate button for each module/exercise that will prepopulate the module/exercise in addition to the submitter?

Here is an example with a button that populates only the user at the top, a button that populates the submitter and module in the middle, and two buttons that populate the exercise and submitter at the bottom.
![image](https://github.com/apluslms/a-plus/assets/49596400/7b8f9b9b-a3a8-47fd-a363-1f90506a43dc)

Is this acceptable? Is the top button even needed if the other buttons are present?

This is what it looks like after clicking the first exercise button 
![image](https://github.com/apluslms/a-plus/assets/49596400/71e00dbf-e47d-4ac4-a081-5c9686b6bd23)

**Comment by Mankro** [comment]
@jsorva would you please comment to Tuomas's ideas above?

**Comment by Mankro** [comment]
Do we also need this shortcut to adding deviations in the inspect submission page (inspect view)? The inspect view is connected to submitters and one assignment, so that those could be prefilled in the add deviation form.

**Comment by jsorva** [comment]
@lainets 
Thank you for exploring the design space! 
If the other buttons are present, the top button is unnecessary. In practice, the weekly/module button would see the most use, so that’s definitely a nice one. The exercise-specific buttons take up some space (especially with a long text) but they would also be useful.

**Comment by jsorva** [comment]
> Do we also need this shortcut to adding deviations in the inspect submission page (inspect view)? The inspect view is connected to submitters and one assignment, so that those could be prefilled in the add deviation form.

It’s not a bad idea. Not necessary IMO but I believe I would sometimes use it, yes.
