### ISSUE TITLE
Add an option to delay the publication of solutions

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1126]
In various courses, solutions are published exactly at each module’s deadline. It is exactly around that time when student requests for extensions flood in. It might be a good idea to publish solutions a bit later, to allow time for processing those student requests.

So I’d like to see an option where one could set a delay for the publication of solutions. (E.g., a default for the whole course; customizable my module.) My personal preference would be to set the delay in minutes, but I’d be OK with something else too.

**Comment by Mankro** [comment]
This was implemented in #830 & #880.

Check out the instructions for `reveal-model-solutions`:
https://github.com/apluslms/a-plus-rst-tools/blob/master/README.md#4-submittable-exercise

**Comment by jsorva** [comment]
Great — I wasn’t aware of that at all! I will definitely use this in the future.
