### ISSUE TITLE
Improve UI for creating multilingual news items

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1134]
AFAIK, it’s currently rather inconvenient to create multilingual news items (that get displayed in one language or other depending on the user). In O1, for example, we use hand-written HTML tags in each such news item. It’s not a massive chore, but it’s still rather pointless work. Since it would be presumably quite easy to improve things, I hope it gets done at some point.

**Comment by Mankro** [comment]
Proper multi-language support is needed first from the issue #517.
