### ISSUE TITLE
Make the unit super-obvious in time-spent fields

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1143]
Feedback questionnaires may have a special field for time spent. Students are expected to type this in as an integer that represents minutes, and generally do. However, there’s some evidence that students occasionally fail to spot the instruction to use minutes and use hours instead, which messes up the data. 

It would be nice if the unit was super-obviously displayed within the input field itself. E.g., the empty field could initially hold a grayed-out placeholder such as "N minutes", which would disappear on keyboard focus. The word "minutes" could then be displayed after the user’s input (within the field) as soon as the user types in something. This sort of thing works very nicely in some GUIs/pages.

(I’ve written this under the assumption that the unit is minutes. If other teachers use some other unit, the unit should be configurable.)

**Comment by Mankro** [comment]
Jutut feedback forms are rendered in the mooc-jutut service, though Jutut loads the structure of the feedback form from the A+ API as JSON. 

@oseppala started to investigate how to add a placeholder attribute to the timespent input element.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#placeholder
