### ISSUE TITLE
Improve logging on SISU interactions

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#1157]
- SISU logs should show also the removed students when enrollments are updated
- Logs should show which course failed, when query fails

**Comment by Mankro** [comment]
> SISU logs should show also the removed students when enrollments are updated

easy to add here?
https://github.com/apluslms/a-plus/blob/8b0d6e6e55697c215805cf8357d8fde27f515596/course/models.py#L949-L950

> Logs should show which course failed, when query fails

Is the query done in the Sisu plugin?
https://github.com/apluslms/aalto-sisu/blob/master/aalto_sisu/sis_aalto.py

**Comment by PasiSa** [comment]
I don't think we need to touch Sisu plugin after all.
