### ISSUE TITLE
Empty date fields when adding a course instance results in 500 internal server error 

### ISSUE THREAD

**Issue by lainets** [apluslms/a-plus#1174]
Saving a new course instance with the required date fields left empty causes an internal server error. Seems like the field validation doesn't check for empty fields.

**Comment by Mankro** [comment]
The crash occurred in the Django admin page for creating new CourseInstances. The code in `CourseInstance.clean()` clearly tries to use the mandatory starting and ending times before checking if the values are `None`. The less than comparison with the `None` value causes a crash.

https://github.com/apluslms/a-plus/blob/7e4bd40f0df6653b51953ab5bf0100ed681f0f51/course/models.py#L704
