### ISSUE TITLE
New course instance copies the SIS id from the old instance if no new SIS id is set

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#1177]
When a teacher creates a new course instance under the Edit course - Instances page, it is possible that the new course instance copies the SIS id and enroll settings from the old course instance. This means that the students registered to the old course in SISU are also added to the new A+ course instance, which is absolutely not wanted. The old SIS id is copied to the new course if the teacher does not select anything in the SIS fields on the `CloneInstanceForm`. This is actually common since the SIS course ids are usually not yet available, e.g., in May for the coming autumn courses.

The new A+ course instance should have an empty SIS id after creation if the teacher has not selected any new SIS id in the `CloneInstanceForm`.

Currently, the code sets a new SIS id only when the teacher has selected something in the form:
https://github.com/apluslms/a-plus/blob/2a339fc4d7874340a2d4ea946d9b43e7a66b79a4/edit_course/operations/clone.py#L93-L94

**Comment by ihalaij1** [comment]
I'm pretty sure the fix is to set ``instance.sis_id = ''`` and ``instance.sis_enroll = False`` in clone.py before ``instance.save()`` is called.

**Comment by PasiSa** [comment]
> I'm pretty sure the fix is to set `instance.sis_id = ''` and `instance.sis_enroll = False` in clone.py before `instance.save()` is called.

Yep, correct. I can push the fix shortly.

**Comment by Mankro** [comment]
@PasiSa 
https://github.com/apluslms/a-plus/commit/8ab057c5e05f1bea2320a6c61e6bee5c296faae5

```python
    instance.sis_id =''
    instance.sis_enroll = False
```

Unfortunate whitespace mistake: missing whitespace after `=`
 `sis_id =''`
