### ISSUE TITLE
User not selected when clicking "add deadline deviations" on points pages

### ISSUE THREAD

**Issue by lainets** [apluslms/a-plus#1238]
The user points page contains buttons to add deadline deviations with user and exercise/module preselected. However, the user is not preselected.

**Comment by Mankro** [comment]
Caused by the different id values for the same user in the models User and UserProfile. Need to be careful so that the ids refer to the correct table and users.

**Comment by lainets** [comment]
Apparently that is not the only issue as they still don't get prefilled even with the id changed.

**Comment by lainets** [comment]
Turns out the `UsersSearchSelectField` used by `BaseDeviationForm` searches the user profiles using the user id instead of the profile id. In essence, `UsersSearchSelectField` was expecting a user id while the code setting the initial queryset was expecting a profile id.
