### ISSUE TITLE
Teacher-facing UI message is technically incorrect in the Inspect view 

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1269]
This is a small thing, but anyway. 

As illustrated below, the Inspect view may claim that there are higher-scoring submissions, even though there aren’t.

![image](https://github.com/apluslms/a-plus/assets/8523129/17ab61e3-1a90-4cbe-bf83-f5f91d4ed912)

**Comment by Mankro** [comment]
But there are higher-scoring submissions! You have selected a submission in the unofficial status, thus its score (zero) is not any higher than the score of the other submissions in the ready status. Since unofficial submissions do not affect grading, their score is always zero despite the points that the grader awards them.

**Comment by jsorva** [comment]
> But there are higher-scoring submissions! You have selected a submission in the unofficial status, thus its score (zero) is not any higher than the score of the other submissions in the ready status. Since unofficial submissions do not affect grading, their score is always zero despite the points that the grader awards them.

OK, I suppose that’s one way to interpret things. But I’d argue that the phrasing is not at all clear, even if I try to interpret it generously. Also, the literal meaning of the message (~ "There are higher-scoring submissions") is wrong, since there is no submission that scores any higher. IMO, the message should still be changed.

 (But yeah, there are more important things to worry about. I wont belabor the point.)

**Comment by Mankro** [comment]
OK, i opened the issue again. This issue is about changing the message so that it is easier to understand the intended meaning.

**Comment by PasiSa** [comment]
Muskaan is starting to look at this as her first issue. @jsorva would this be better: "Another submission determines the grade for this assignment." (and in Finnish: "Toinen palautus määrittää tämän tehtävän arvosanan.")? Or any other proposals?

**Comment by jsorva** [comment]
> Muskaan is starting to look at this as her first issue. @jsorva would this be better: "Another submission determines the grade for this assignment." (and in Finnish: "Toinen palautus määrittää tämän tehtävän arvosanan.")? Or any other proposals?

I’m assuming that this is a generic message that gets shown both when 1) there actually is a higher-scoring submission and 2) the unofficial-submission scenario that I depicted above. If so, then your suggestion is OK by me. 

(Even better messages could be shown if those two two scenarios were dealt with separately, but I suppose there’s no pressing need to do that.)
