### ISSUE TITLE
The Cancel button in Add Deadline Deviations behaves surprisingly

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1278]
Just a detail:

If I go to a student’s page, there are now links ther to add deadline deviations for that particular student. (This is super-useful.) 

Now say I click one of those buttons but then wish to cancel. There’s the cancel button there on the add deviations page, but that doesn’t actually cancel my action in the sense of taking me back where I was. It instead sends me to the list of all deviations (which page, in the case of the O1 course, either crashes with a Bad Gateway or takes approximately forever to load).

**Comment by Mankro** [comment]
The cancel button is simply a link to the deviation list page. There is (currently) no implementation for remembering where the user came from to the form. It is possible to implement it. The "add deviation" form view could read a redirect target from a GET query parameter and use that after the form is submitted. If there is no query parameter, the default could be the list page like it has been. The links to the "add deviation" form would then need to add the GET query parameter to the URL.

The fact that the deadline deviation list loads very slowly (or crashes) on your course is not really related to this issue, but it of course makes the cancel button even more frustrating.
