### ISSUE TITLE
The word wrap button doesn’t work when inspecting student submissions

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1281]
When inspecting student submissions, these buttons are shown:

![image](https://github.com/apluslms/a-plus/assets/8523129/0e425953-c8e8-4249-9456-0f0656265ae6)

However, the _Word wrap_ button fails to work, and produces this in the Console:

![image](https://github.com/apluslms/a-plus/assets/8523129/2b93e90a-1033-4416-911d-a325c3a8e247)

I’ve also had difficulties with the _Copy to clipboard_ button in the same view but that may be related to the specifics of my own setup, so if it seems to work for everyone else, maybe the problem is at my end.

**Comment by Mankro** [comment]
There is another report of the broken "word wrap" button in the internal ticket system:
https://rt.cs.aalto.fi/Ticket/Display.html?id=24561

**Comment by Mankro** [comment]
@jsorva about the "copy to clipboard" button, I haven't seen issues in it. The "word wrap" button has been fixed.

**Comment by jsorva** [comment]
OK. After hearing another comment from a student, I’m reasonably sure that that symptom — experienced by me and this student — has to do with pasting into IntelliJ IDEA and is not related to A+. Please ignore that part of this issue. Thanks for confirming!
