### ISSUE TITLE
Deadline extensions misbehave if they cross daylight savings time start/end 

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1287]
It’s not uncommon to grant students long deadline extensions — one week or more. This happens for various reasons (e.g., medical issues, groups of high school students with a different schedule, etc.)

A+ supports this by allowing teachers to give an extension measured in days. The intuitive interpretation of this is that if a deadline at X o’clock is extended by Y days, the new deadline will be at X o’clock the same time, but Y days later. This is, however, not necessarily what happens.

It appears that if daylight savings time starts or ends during the deadline extension, the new deadline will be at X-1 or X+1 o’clock. For example, if I give a 7-day extension to our Wed 6pm deadline from late October to early November, the student will be able to submit until Wed ***5pm*** the following week.

The practical consequence is that teachers should be constantly aware of upcoming clock-windings. (And of course they won’t remember.) And the student will see confusing info about their deadline extension and won’t be able to submit their work close to the extended deadline that was intended. 

This also affects the (again not-super-rare) case that multiple deadlines are extended at the same time. For example, there are cases where a student’s entire course schedule needs to be shifted by, say, three weeks. The convenient way to do this is to go to the DL extension form, select all the modules and mark 21 days as the extension. What then happens is that the September, October, and December deadlines will shift appropriately but the November deadlines will be one hour too early.  

Suggested solution: When using the Days field in the form, automatically check whether a daylight savings boundary is crossed and adjust the extension length accordingly.

(Side note: in principle, someone could decide to give a week’s extension by extending the DL by 10080 minutes instead of 7 days. Before the Days field was added, that was indeed the only way to do it. But I think that strategy can now be considered an exotic relic of the past, and the fix could focus on just the Days field that actually matters.)

**Comment by jsorva** [comment]
This issue has been closed, but the fix does not seem to be working in production.

In the pic below, I have previously given my own test account a 3d extension from Wed 23rd 18:00 to Sat 26th 18:00. Now I’m about to override it with a 4d extension, until Sunday, which crosses the daylight savings border. As shown, the new deadline is at 17:00, which is not what was intended.

![image](https://github.com/user-attachments/assets/715832e6-0f04-45e9-b8c2-496bfc56ee57)

**Comment by ihalaij1** [comment]
Reopening for investigation.

**Comment by ihalaij1** [comment]
@jsorva I think the previous fix only fixes the problem when adding a new deadline deviation, but not when overriding a previous one so that it crosses daylight savings border.

**Comment by ihalaij1** [comment]
@jsorva This is now fixed in PR #1422.
