### ISSUE TITLE
It might not be possible to clear notifications from courses that are not accessible by the student

### ISSUE THREAD

**Issue by oseppala** [apluslms/a-plus#1289]
In case a course has ended and a student has no access to the course the student might not be able to clear a notification from the said course. This can happen if the course was closed before the student read the notifications.

Either notifications need to be cleared if a course is made inaccessible or they need to be filtered out of the list of shown notifications.

**Comment by Mankro** [comment]
@oseppala Have you tested this recently? Is this really a bug in the current version? We already closed this issue one month ago: #683. This new issue looks like an exact duplicate. There is nothing new here.
