### ISSUE TITLE
LTI: points from ACOS assignments are not delivered to LTI Platform

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#1305]
When an ACOS exercise is submitted and A+ operates as an LTI tool, the points are not sent back to LTI platform (typically MyCourses in Aalto). [send_lti_points in lti_tool/utils.py](https://github.com/apluslms/a-plus/blob/master/lti_tool/utils.py#L77) fails to find the launch data with needed information, and LtiException is raised. The difference to other kinds of exercises that do work with LTI is, that with ACOS exercises the submission metadata does not contain 'lti-session-id', but only 'lti-launch-id', which does not seem to be sufficient in this case. The session-id should be set [here in create_from_post](https://github.com/apluslms/a-plus/blob/8f856141f3af955668df001942a72c696f9a9722/exercise/submission_models.py#L259-L263) method.

A possible (but perhaps not ideal) solution could be to have the ACOS server echo the original initiating lti-session-id in the similar way than it echoes the lti-launch-id, as implemented in earlier [a-plus](https://github.com/apluslms/a-plus/commit/7f1d846c1a0163fa7f9fd212b9131b66d9fed7d9) and [acos-aplus](https://github.com/acos-server/acos-aplus/commit/e51c945642a97737907d71cc617d2dd4c4e8e9f7) commits.

Fixing this should be quite high priority, because there are ongoing courses depending on this feature, that is intended to replace the functionality of the Moodle-Astra plugin that will be rolled out soon.

**Comment by Mankro** [comment]
I understood that @PasiSa is working on this so I assigned the issue to him.

**Comment by PasiSa** [comment]
Having problems setting up a proper environment for locally testing and developing this, I ran out of time, and therefore unassigning myself.
