### ISSUE TITLE
potential keyerror in news item language

### ISSUE THREAD

**Issue by jykesaviaGNH** [apluslms/a-plus#1356]
After an update to version 08368758104c3ef03bcb9a992b187d68c2a221da
this multiple language news item gave an keyerror:
https://github.com/apluslms/a-plus/blame/08368758104c3ef03bcb9a992b187d68c2a221da/news/templatetags/news.py#L35

Database migration was run, but it seems that memcached version without the langauge was still present.

**Comment by murhum1** [comment]
You should indeed clear the cache when upgrading to newer versions, so that remnants from the old cache don't cause conflicts. I understood this was resolved by clearing the cache - closing the issue.
