### ISSUE TITLE
Submission feedback at the deadline time, if points > 0

### ISSUE THREAD

**Issue by teemulehtinen** [apluslms/a-plus#1369]
Reuse the e-exam feature "reveal-submission-feedback = deadline" for use in course content. **Motivation:** Shift the responsibility of properly testing the submitted code to the student. Prevent generating, testing, and fixing code using LLMs and automated feedback. **Required changes:**

* Add an option to show feedback with 0 points immediately, which enables the development of sanity checks that fail if a student submits e.g. the template code without changes, a differently named program, or something else that prevents running the real grading tests.
* The exercises that use feedback at the deadline must have a note and visible distinction from those that immediately show feedback. This may need to be different than in the e-exam case.
* Feedback at the deadline implies grading mode is points for the last submission. When late submissions are allowed the grading mode needs to be: the last submission in time or better from late submissions with the late penalty applied.

**Comment by etanttila** [comment]
There already are several options in A+ for revealing feedback after the deadline
![image](https://github.com/apluslms/a-plus/assets/50318434/f0ab2c08-06a1-4369-b6b2-bf5c1ed237ee)
So would this suggested option be an additional alternative in addition to the existing ones, or would you suggest that some of the existing ones would be changed to behave in the manner you indicate?

**Comment by etanttila** [comment]
(It seems like teachers see feedback immediately even if the settings are set to have it as delayed feedback, so if you want to test how it appears to the student, you actually need to test it with a student.)

Before submitting, there indeed is no information at all that feedback will not be provided immediately, which certainly is problematic. (At least I as a student would be really annoyed to not know that beforehand.)
![image](https://github.com/apluslms/a-plus/assets/50318434/f5648300-94eb-4620-ad36-9a63235e205b)



After submitting, there is a notification that the feedback will be published later
![image](https://github.com/apluslms/a-plus/assets/50318434/157223b2-1182-489a-a644-54cba2153df7)

If only the last submission is graded, there is a notification that only the last submission is graded before submitting (this remains also after submitting)
![image](https://github.com/apluslms/a-plus/assets/50318434/3f2b749b-0c86-4e37-80a8-b574cec52750)

After submitting:
![image](https://github.com/apluslms/a-plus/assets/50318434/63d4089a-b963-4120-b375-8078a95bb5c1)
However, if the page is reloaded, the green box disappears, so there is no info (other than the question mark in the points) to indicate feedback will be provided later.

Indeed, it should be more transparent (and apparent to students!) if feedback is delayed (e.g. to deadline).

**Comment by teemulehtinen** [comment]
I would add a separate checkbox "Always reveal feedback worth 0 points immediately" next to the delay minutes (there are different fields that only appear for certain reveal modes already).

When the visibility/notes for when to expect feedback are designed, we must also consider the exam case. The UI should not become annoying or confusing when completing an exam.
