### ISSUE TITLE
Download submissions from an exercise

### ISSUE THREAD

**Issue by mikaelGusse** [apluslms/a-plus#1374]
There are several use cases where being able to easily download all of the submissions from an exercise would be useful. Such as if the teacher wants to do any kind of manual analysis on the student's code, such as checking it for plagiarism using some local tool. Currently the only way to mass-download submissions is through the api with some custom script. 

A way to fix this would be to simply add a button to the "all submissions" view which would download the submissions. Perhaps it could also include some options on whether the user wants just the most recent submission or all of them.

**Comment by oseppala** [comment]
For previous discussion about the topic
#459
#586

**Comment by oseppala** [comment]
And while you are on it, check also the low hanging #733

**Comment by mikaelGusse** [comment]
For Radar+Dolos we want a .zip that has all the submission files straight in the zip without any folders. So the zip would look something like this
![image](https://github.com/user-attachments/assets/e8e7c2cd-d571-4cf6-9d4b-a612203b1901)
And then the metadata would have to look something like this:
![image](https://github.com/user-attachments/assets/75b1bedb-fc8c-43e0-84db-c3f1b00eab51)
(Taken from Dolos documentation (https://dolos.ugent.be/docs/adding-metadata.html#csv-format))

**Comment by mikaelGusse** [comment]
Also it would be nice if you could either pick to download all submissions or just one submission per student (the latest one or the one with most points)
