### ISSUE TITLE
Feature request - batch import of manually graded assignments

### ISSUE THREAD

**Issue by malkamont** [apluslms/a-plus#1375]
Our course is running on A+ and its project section depends to a large extent on manual grading of text-based submissions (mini-essays). With multiple assignments and more than a hundred students, clicking through the manual grading cue is rather tedious and prone to human error, especially as we must first take the text-based submissions out from A+, assign grades, and perhaps tweak our grading criteria for consistency after reading through all submissions.

Adding a feature that would allow for uploading a csv with all scores for all assignments for all students at once (last submission as the grading mode) would be extremely useful.

Many thanks,
Arttu

**Comment by murhum1** [comment]
As mentioned in the separate ticket, there's a batch assessment feature under "Edit Course" --> "Batch Assess". Did you manage to try this out yet to see if it it's sufficient for your use?

**Comment by malkamont** [comment]
I didn’t yet try out that functionality but it seems promising - I’ll come bsck here if I encounter issues.

Thanks again!
