### ISSUE TITLE
List courses where the user is an assistant in the API

### ISSUE THREAD

**Issue by jaakkonakaza** [apluslms/a-plus#1397]
The endpoint https://plus.cs.aalto.fi/api/v2/users/me does not provide information about the courses where the user is an assistant. If the user is not enrolled in a course as a student, the course is not listed in the endpoint at all.

Our plugin checks this endpoint to determine whether the user has access to a course, but due to this it does not work correctly for course assistants.

**Comment by ihalaij1** [comment]
Changes were made in the PR https://github.com/apluslms/a-plus/pull/1403.
Is it okay if the teachers and assistants are listed separately from each other (under `teacher_courses` and `assistant_courses` instead of `staff_courses`)? @jaakkonakaza

**Comment by jaakkonakaza** [comment]
Would `staff_courses` and `assistant_courses` be okay? This way it wouldn't be a breaking change
