### ISSUE TITLE
Menu items should always default to "Course" menu group

### ISSUE THREAD

**Issue by ihalaij1** [apluslms/a-plus#1411]
Currently, if no additional menu group labels have been defined, new menu items go under the "Course" menu group.

If some menu items have a custom menu group label, new menu items go, by default, under the first custom menu group, when they should still go under "Course".

**Comment by James-Leste** [comment]
# Detailed reproduction
## Reproduction 1
### Steps

- create a menu item with group label `label1` and the label `labelitem1`
- create a menu item with empty group label and the label `nonlabelitem1`
- create a menu item with group label `label2` and the label `labelitem2`
- everything else default

### Results

![image](https://github.com/user-attachments/assets/e70244af-9bab-41bb-ae22-0afb3a2bf98f)
***correctly fell into the `label1`***

![image](https://github.com/user-attachments/assets/ffe022b9-3d28-4df6-b6ba-7f6c39e8777a)
***fell into the wrong category***

![image](https://github.com/user-attachments/assets/d4a36b04-a025-40e5-80c2-f746eefc8687)
***fell into the latest the wrong category***

## Reproduction 2 (Reversed sequence)
### Steps

- create a menu item with empty group label and the label `nonlabelitem1`
- create a menu item with group label `label1` and the label `labelitem1`
- create a what iten with group label `label2` and the label `labelitem2`
- everything else default

### Results

![image](https://github.com/user-attachments/assets/c8c35a08-5048-48a8-9e3e-b1720352758f)
***correctly fell into default group***

![image](https://github.com/user-attachments/assets/762f3b68-a705-4336-9d09-a290303e749d)
***jumped into the wrong group***

![image](https://github.com/user-attachments/assets/634b408d-6f3d-4b4e-ac73-31bff21f5b25)
***jumped into the latest labelled group***

## Bug description in short
All the menu items that have being set an empty `menu group label` will automatically categorized to lastest added menu group on the sidebar menu.

**Comment by James-Leste** [comment]
I discovered that the original code does not intend to make items without a group label under the `Course` section by default. Instead, because the label is an empty string and it coincidentally seems that they go under the `Course` label by default. In this case, should I put them under the `Nolabel`(Or some other names) section for those menu items instead of under the `Course` section by default.
