### ISSUE TITLE
New fields for the ZIP download csv

### ISSUE THREAD

**Issue by oseppala** [apluslms/a-plus#1427]
When downloading user submissions in a zip file the file names and types are changed to filenames of the format: userid_submission_file_1. While this allows placing them in the same directory it requires the end user to rename the files back to their original names.

Adding two new columns to the csv file would greatly help the external tools:

filename in the submission form
filename of the file that was submitted through the form

suggested names for the two fields are _form_name_ and _original_name_ but

**Comment by mikaelGusse** [comment]
Also would be nice to have:
- submission_id
- points
- student name
- which submission (number)
