### ISSUE TITLE
Course description

### ISSUE THREAD

**Issue by ihantola** [apluslms/a-plus#17]
Add course description field to the Course (and optionally to the CourseInstance).  Add this course description to the course link on the main page. Ideally course description could be taken from CourseInstance and this does not exist (or is empty), then from the Course. 

See https://github.com/vkaravir/a-plus/commit/aee39b7521c81ae60299ce235d77379ff64d6c65 where lorem-ipsum course description was removed.

**Comment by Mankro** [comment]
It is a bit questionable whether we want formal course descriptions in A+. The text on the A+ course front page can already be modified by teachers. Formal course descriptions are defined in WebOodi. The text could be retrieved from WebOodi and rendered in A+ if that seems to be useful.

**Comment by annirytkonen** [comment]
This is a good idea. Currently at Aalto, course descriptions are created in Sisu and visible also in MyCourses, where teachers can edit them. Each Aalto course has a workspace in MyCourses (not yet in 2012, but for some years now :). There are existing practices in other systems, and I don't perceive as meaningful to implement the same features in multiple systems, so I close this issue.
