### ISSUE TITLE
Missing UI for Adding MaxSubmissionDeviations

### ISSUE THREAD

**Issue by LassiHaaranen** [apluslms/a-plus#184]
Teachers' have a user interface for adding deadline deviations (Edit Course -> Deviations). This view should include the option to add max submission deviations as well.

**Comment by teemulehtinen** [comment]
These days staff can add extra submissions one at a time from the inspect submission view.

**Comment by raphendyr** [comment]
Closing this as there is the `+1` button. If there appears to be need for a better UI, then a more detailed issues with an usecase should be created.
