### ISSUE TITLE
Submission filtering and charsets

### ISSUE THREAD

**Issue by teemulehtinen** [apluslms/a-plus#190]
Filter with ä or ö so that the filtering word is stored in a cookie. Navigate away so that the cookie keeps the value. Return and the session and filtering cookies get rotten and browser is thrown into a redirect limbo. (Only way to enter the page is to remove the latest cookies - one cannot see the cookie in inspector as you cannot get to the URL).

**Comment by raphendyr** [comment]
The cookie should be removed, or data should be moved to local storage.

**Comment by Mankro** [comment]
Does A+ really uses cookies in some submission filtering view or is this completely outdated?

**Comment by annirytkonen** [comment]
seems to be outdated; I close the issue.
