### ISSUE TITLE
Requests package doesn't us system cert dir, thus trusted certs are not updated often enough

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#218]
**Current version might be security issue** as if some CAs are not trusted anymore, it doesn't update to a-plus installations.

Requests module tries to use `certifi` to report path to certs, but that is not installed into our virtualenv. Neither of those packages would provide the real system certificates path. Both packages have patch in at least debian family to point into system cert dir. Thus if any of those packages can be used from system wide installation (and is installed there), then we would use system certificates (updated with security patches automatically).

Solutions

a) use `virtualenv --system-site-packages` to add all system wide packages to the path and install python3-certifi.

b) Manually link certifi into virtualenv using `ln -s -T /usr/lib/python3/dist-packages/certifi venv/lib/python3.4/site-packages/certifi` (some magic would be handy here).

ps. excample magic

``` python
import certifi, os
print(os.path.dirname(certifi.__file__))
```

**Comment by raphendyr** [comment]
One solution from mooc-jutut installation instructions:

```
sudo -H -u $user sh -c "
  for p in certifi psycopg2; do
    for d in $venv/lib/python3*; do
      rm \$d/site-packages/\$p-*.egg-info
      psrc=\$(python3 -c \"import \$p; print(\$p.__file__)\")
      ln -s -t \$d/site-packages/ \${psrc%/*}*
    done
  done"
```

Where `user` is user used for running gunicorn and `venv` is virtualenv installation path.

**Comment by raphendyr** [comment]
Unsecure installation:

```
$ python3 -m certifi.core
/usr/local/lib/python3.5/dist-packages/certifi/cacert.pem
```

Secure installation:

```
$ python3 -m certifi.core                                                                                                                                                                                  /etc/ssl/certs/ca-certificates.crt
```

**Comment by annirytkonen** [comment]
@Mankro checks the status before we do anything.

**Comment by Mankro** [comment]
This doesn't seem to be an issue any longer.

The A+ server has certifi installed and it uses the path under `/etc/ssl/certs`.
Certifi is bundled in the Python requests package.

We should check that the certifi package is updated at least once a year.

From https://docs.python-requests.org/en/master/user/advanced/#ca-certificates:

> ## CA Certificates
>
>Requests uses certificates from the package [certifi](https://certifiio.readthedocs.io/). This allows for users to update their trusted certificates without changing the version of Requests.
>
>Before version 2.16, Requests bundled a set of root CAs that it trusted, sourced from the [Mozilla trust store](https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt). The certificates were only updated once for each Requests version. When certifi was not installed, this led to extremely out-of-date certificate bundles when using significantly older versions of Requests.
>
>For the sake of security we recommend upgrading certifi frequently!

**Comment by raphendyr** [comment]
Assuming the process uses docker images now-a-days, then this is solved via that process too.

At least, assuming you build new images time to time, which should be done to ensure the supporting packages get their security updates too.
