### ISSUE TITLE
Reading the wait meta argument in the grader protocol

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#279]
In the file `a-plus/exercise/protocol/aplus.py` line 128 (`function parse_page_content`):
```
if remote_page.meta("wait"):
    page.is_wait = True
```

If the remote page meta value for wait is "0", then the if statement above is still true. For example, `<meta name="wait" value="0" />`. Is this correct behaviour? Now the remote page must not have the wait meta value at all in order to signal "do not wait". 

In the mooc-grader, this meta argument is set in `mooc-grader/access/templates/access/exercise_head.html` as `<meta name="wait" value="{{ result.queue }}" />`. `result.queue` equals the async queue length at the time when the submission was queued for grading. Would it make more sense to use just a boolean value for wait instead of the queue counter? Well, in my test server the queue length is always reported as zero but that is probably a queue configuration issue.

**Comment by teemulehtinen** [comment]
If the meta 'wait' exists A+ javascript will poll for the asynchronous result 9 times in a minute with growing delay. The value is ignored so effectively it acts as a boolean flag and there is no reason to use queue length there. The logic if A+ should poll for particular submission is left for the grader.

For clarity it could be refactored but then one should rather use "yes" and "no" than integers, e.g.
```
wait = remote_page.meta("wait")
page.is_wait = wait and wait != "no"
```
