### ISSUE TITLE
Support for two levels of trust for services

### ISSUE THREAD

**Issue by vkaravir** [apluslms/a-plus#29]
Currently we either have to trust all or none of the services A+ uses. I suggest a two-level trust model for the services:
- services that are trusted: allow feedback and content to be unfiltered (or at least sanitized using more relaxed set of rules)
- services that are not trusted: more strict sanitation that allows only certain HTML content in feedback/description filtered with a white-list

Probably easiest to implement by having a list of trusted service URLs (or domains) in settings.

**Comment by annirytkonen** [comment]
we close the oldest issues.
