### ISSUE TITLE
Error upon course json configuration e.g. "Apply"

### ISSUE THREAD

**Issue by teemulehtinen** [apluslms/a-plus#302]
Sometimes the update fails with below error. A fix is to manually remove the obsolete "hidden" entries, that have 99999 weight, before doing the "Apply" again.
```Server error: insert or update on table "exercise_learningobject" violates foreign key constraint "D5881233ddf2ad4d825c0b6aef345c53" DETAIL: Key (parent_id)=(14205) is not present in table "exercise_learningobject".```

**Comment by raphendyr** [comment]
This must be fixed, before A+ can be configured automatically

**Comment by Mankro** [comment]
This issue is old so one must first check if this bug can be replicated. The error message implies that exercises are nested since they have parents. Chapter learning objects are parents to exercises (base exercise learning objects) in typical RST courses.

**Comment by Mankro** [comment]
I close this as a duplicate. This was created before #768, but that one has a longer explanation.
