### ISSUE TITLE
Course-wide MOTD and System-wide alerts

### ISSUE THREAD

**Issue by oseppala** [apluslms/a-plus#34]
Adding a course-wide message of the day and a system-wide alert to A+.

The message of the day could be shown on the course main page. "Service break today at 16PM", "Third exercise round opens tomorrow" etc...

The system-wide alert would be shown on most pages. "Service break starts soon! Save your work."

**Comment by raphendyr** [comment]
These are implemented. See settings `SITEWIDE_ALERT_TEXT` and `SITEWIDE_ADVERT` in https://github.com/apluslms/a-plus/blob/master/aplus/local_settings.example.py.

**Comment by raphendyr** [comment]
> "Third exercise round opens tomorrow"

Actually, that is not implemented, but well have course news, which might be ok. If that is not enough, please raise an issue exactly about that usecase.
