### ISSUE TITLE
Future not-yet-open exercises not returned from API with teacher's token

### ISSUE THREAD

**Issue by piehei** [apluslms/a-plus#341]
If you're using a teacher's API key, a URL like this https://plussa.fi/api/v2/courses/{ID}/exercises/ does NOT return exercises that are both in the future AND belong to a module that is not open. So it's not a list of all exercises belonging to a course.

Is this intentional or an error?
Superuser token returns everything which feels like what the teacher would want, too.

**Comment by raphendyr** [comment]
API should return everything and then who ever is parsing them should handle hidden and not yet open exercises correctly.

Technically, hidden exercises could be returned for the student too as otherwise the API isn't very consistent.

**Comment by annirytkonen** [comment]
@Mankro check if this is still relevant - most likely it's not and can be closed.

**Comment by Mankro** [comment]
Duplicate #549.

This has been fixed.

Students can not see modules that haven't opened yet in the API. This has been intentional thus far.
