### ISSUE TITLE
Submitting exercise-specific post parameters to grader

### ISSUE THREAD

**Issue by oseppala** [apluslms/a-plus#35]
It could be useful to give graders parameters via post params that affect the behavior of the grader/select an exercise/etc.

Moreover these parameters could include files submitted through post. For example there could be a generic multiple choice grader that is given an XML file that contains the choices and the correct result.

Submitting a user-unique hash as ome post parameter would allow user-specific exercises without compromising privacy.

**Comment by raphendyr** [comment]
The `ExerciseWithAttachment` for now can be used for some of the use cases. In addition, A+ is providing pretty wide set of information to the assessment service. This issue doesn't seem to be relevant as is anymore, so I close it.

P.s. future assessment interface versions will look into better personalization support.
