### ISSUE TITLE
Source frontpage content from first RST file

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#353]
Frontpage content is currently only edited using course management, but it should be moved to aplus.json and generated from RST files in the first place.

**Comment by piehei** [comment]
And also from index.yaml I suppose? We have *many* courses using the yaml format :-)

**Comment by raphendyr** [comment]
yaml is intermediate step, so yes.

**Comment by annirytkonen** [comment]
old and non-critical - to be closed due to old age.
