### ISSUE TITLE
Feature request: send email when teacher adds news

### ISSUE THREAD

**Issue by piehei** [apluslms/a-plus#377]
Hi

It would be very nice to be able to notify students via email when teacher adds news. This should be an option so the teacher could decide on case-by-case basis whether to send the email or not.

What do you think?

Thanks!

**Comment by raphendyr** [comment]
About notifications from my memory from previous thinking.

levels:
 * priority
 * important
 * not so imporant

notification settings per student:
 * student can state do they receive email from different notification levels or should they get dggest oer day for example

notification sources:
 * grader can define notification level for the feedback notification
 * different other notification sources have opinion to be higher than normal (e.g. one level up)
 * priority is recerved for really high importance stuff, so students would most of the time keep email notifications for it, or that level could be always forced (only if there is less than few emails per year).
