### ISSUE TITLE
Missing time on late submission deadline

### ISSUE THREAD

**Issue by henkka14** [apluslms/a-plus#382]
Time is not shown on late submissions, only the date can be seen. Jaakko tasked me to create an issue for it.

**Comment by raphendyr** [comment]
![ongelma](https://user-images.githubusercontent.com/2327687/51984772-ccc1cc00-24a4-11e9-9faa-1ece76157504.png)

Datetime rendering in this message box

**Comment by Mankro** [comment]
Looks like a very small task.
@alalav1 can work on this.

**Comment by alalav1** [comment]
Time is missing in three locations: User results page, exercise pages and exercises themselves.

**Comment by alalav1** [comment]
The `late_time` values formatting changes in the `blocktrans` block in the html template. The formatting can be overridden: `deadline=current.late_time|date:"D Y m d, P"` https://docs.djangoproject.com/en/dev/ref/templates/builtins/#date , but then we cannot use different formatting for finish and english.
One solution is that we get rid of the block trans and use normal trans block. Then the date couldn't be in the middle of the sentence.

**Comment by alalav1** [comment]
In the exercises:

Date is formatted in the `once_has_access` function:
```
_("Deadline for the exercise has passed. Late submissions are allowed until {date} but points are only worth {percent:d}% of normal.").format(
                date=date_format(d),
                percent=self.course_module.get_late_submission_point_worth(),
            )
```
The default formatting consider the language and uses the correct format. However, only the date is shown, not the time.

**Comment by Mankro** [comment]
> In the results page and module pages:
> 
> The `late_time` values formatting changes in the `blocktrans` block in the html template. The formatting can be overridden: `deadline=current.late_time|date:"D Y m d, P"` https://docs.djangoproject.com/en/dev/ref/templates/builtins/#date , but then we cannot use different formatting for finish and english.
> One solution is that we get rid of the block trans and use normal trans block. Then the date couldn't be in the middle of the sentence. This is not a problem, since the two trans blocks gives some flexibility how we can arrange the texts. If we are ever planning to add more than just two languages, this kind of solutions would be trickier and more vulnerable. But as far as I know, that is not going to happen in some time.

Using two trans blocks to add a date in the middle of the sentence sounds like a bad, hacky solution. Don't do that, please. There must be a way to format dates without using multiple trans blocks.

**Comment by alalav1** [comment]
> > In the results page and module pages:
> > The `late_time` values formatting changes in the `blocktrans` block in the html template. The formatting can be overridden: `deadline=current.late_time|date:"D Y m d, P"` https://docs.djangoproject.com/en/dev/ref/templates/builtins/#date , but then we cannot use different formatting for finish and english.
> > One solution is that we get rid of the block trans and use normal trans block. Then the date couldn't be in the middle of the sentence. This is not a problem, since the two trans blocks gives some flexibility how we can arrange the texts. If we are ever planning to add more than just two languages, this kind of solutions would be trickier and more vulnerable. But as far as I know, that is not going to happen in some time.
> 
> Using two trans blocks to add a date in the middle of the sentence sounds like a bad, hacky solution. Don't do that, please. There must be a way to format dates without using multiple trans blocks.

We found a solution using `deadline=current.late_time|date:"DATETIME_FORMAT"`, which uses patterns determined in the format files.
