### ISSUE TITLE
Point cache invalidation bug has returned

### ISSUE THREAD

**Issue by piehei** [apluslms/a-plus#383]
The bug that was (at least it seemed so) fixed in PR 318 (https://github.com/Aalto-LeTech/a-plus/pull/318) has returned. Or maybe something new but very similar has come up.

In a nutshell:

1. student submits something
2. feedback page shows completion, success, points 
3. student goes back to the course front page that lists all exercises and their points
4. student does NOT see points/completion in the exercise that was just completed in previous steps
5. student resubmits
6. points are now shown correctly everywhere

I don't have time to dig in for this. Just reporting here so that it doesn't go unnoticed etc.

:)

**Comment by raphendyr** [comment]
There can be race condiftion here:
  https://github.com/piehei/a-plus/blob/master/lib/cached.py#L54

Not sure if we should compare the datetime of the update after the `add` to see which generation was started later. If our data was generated later, then overwrite the current value with it.

**Comment by raphendyr** [comment]
Yep. My commit actually broke the one important logic in the code. Sadly, I don't remember why I made that mistake, but I do remember thinking that logic for a while.

I'll fix this by reverting to the correct invalidation logic. I'll try to write a test for this too, so I can be sure for few race conditions like if two threads are regenerating the data at the same time (and if that matters at all).

**Comment by raphendyr** [comment]
Can you check if that commit seems to fix the issue for you? Last 3 commits should be compatible with 1.4.4.

**Comment by raphendyr** [comment]
Let's assume, that this is working.
