### ISSUE TITLE
How to add comments to each exercise？

### ISSUE THREAD

**Issue by o5728492** [apluslms/a-plus#410]
How to add comments function to each exercise？

**Comment by Mankro** [comment]
Can you elaborate what you mean?

**Comment by o5728492** [comment]
In each exercise, add a text box where you can enter text and submit it. The entered text is displayed below the text box.
Both staff and student can then enter text in the text field to submit. This way they can have some communication, like comments.

![image](https://user-images.githubusercontent.com/32882824/71152653-faa53000-2271-11ea-8be7-6dc958e7c129.png)

Just like the content of this page

**Comment by Mankro** [comment]
Questionnaire exercises may have text fields. However, course staff should not write their comments in the submission fields. They can write write assistant feedback to the submission in the "inspect submission" page. 

There is a separate service for feedback questionnaires that allows the course staff to write comments back to the student. It is called mooc-jutut: https://github.com/Aalto-LeTech/mooc-jutut

**Comment by raphendyr** [comment]
I presume you want open comments between students. That is something the A+ itself doesn't support. It's also usecase that isn't yet experimented with. That said, you could add iframe to the chapter page and create a service (or use e.g. phpBB) that operates within the iframe and does what ever messaging you want (e.g. chat with websockets).

I prototyped seemless iframes with A+ in mind, so you could use that as basis for setup for above. https://www.niksula.hut.fi/~jaakko/seemless_frames/

We (Aalto) has been using tools Code Vault (student to staff code paste), piazza.com, slack and telegram for open communication between students and staff. In addition, we utilise mooc-jutut as mix of feedback and interaction. It has been designed for usecase where student may report problems,. misunderstandings or what ever as part of the learning.

I don't personally see any use for open comments for exercises, thus we are not probably looking for in A+ support for it, but as described above, that kind of feature can be implemented.

As a future note, for next redesign of A+, we have designed to include comments as attachments to submissions. Again, that is between the student and staff.

**Comment by o5728492** [comment]
![image](https://user-images.githubusercontent.com/32882824/71661201-7336e100-2d88-11ea-8a0d-11467a858ac9.png)
I need to share a view where one URL contains a parameter. How do I change this parameter to be a not required parameter in views?
![image](https://user-images.githubusercontent.com/32882824/71661401-06701680-2d89-11ea-86ae-44ad1c540aaa.png)
 thank you

**Comment by Mankro** [comment]
I really do not understand the question. You should provide more background on what you are trying to do.

**Comment by o5728492** [comment]
![image](https://user-images.githubusercontent.com/32882824/71702124-9f924200-2e08-11ea-825f-bfb53d24a48f.png)
add a numeric type parameter to this URL
“(?P<parent_id>[\d]+)”
![image](https://user-images.githubusercontent.com/32882824/71702181-f1d36300-2e08-11ea-9aab-931cecd8846a.png)
I added the parent_id_kw variable to the view function and got the value through the get_resource_object method, but now I want the parent_id parameter passed in from the URL to be unnecessary.
I want to not pass this parameter in the URL or pass this parameter in the url
it is like 
commentreply/11
or
commentreply/ 

How can I modify the view function to make the passed parameters unnecessary, like parent id=None

![image](https://user-images.githubusercontent.com/32882824/71702367-08c68500-2e0a-11ea-81f6-da8966fa0b2c.png)

finally,
add a parameter to the following URL or not

var url = "\{\{ exercise|url:exercise-commentsreply \}\}";

<script>
    // 加载 modal
    function load_modal(comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;
        var url = "\{\{ exercise|url:exercise-commentsreply \}\}";
        
        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="'+url+'" frameborder="0" style="width: 100%; height: 100%;></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    }
</script>
{% endblock script %}

**Comment by o5728492** [comment]
In exerciseCommentsReplyView method
Add a parameter，and parameter=None，
and if parameter exist, then get it value 
if parameter does not exist, do nothing for this parameter
thank you

**Comment by Mankro** [comment]
In the URL conf, it is usually best to have multiple routes when you have optional parameters in the URL, such as the reply ID. Multiple routes in the URL conf may refer to the same view class.

https://stackoverflow.com/questions/14351048/django-optional-url-parameters
https://stackoverflow.com/questions/14429500/optional-url-parameters-in-class-based-views

In the view class, the `get_resource_objects` method could check if the ID parameter was supplied in the URL or not.

In Django templates, when you refer to the URL by its name, if you have multiple routes in the URL conf with different names, then those would separate the cases when you have the reply ID and when there is no ID.

**Comment by Mankro** [comment]
Closing since this issue has been inactive for many months.
