### ISSUE TITLE
statistics about the students' submissions and time spent (according to Teemu S.'s specs, i.e., the old Goblin statistics page).

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#414]
The plan: Riku will do a prototype of this in the mooc-jutut feedback system during spring 2020.

**Comment by raphendyr** [comment]
Basic features should be implemented in the open PR https://github.com/Aalto-LeTech/mooc-jutut/pull/11

**Comment by Mankro** [comment]
The time usage app is now available in MOOC-Jutut (November 2020).
