### ISSUE TITLE
UI language fixes

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#417]
A+ UI is full of awkward "kapulakieli" in Finnish. The English is worse still. The whole UI is in need of a thorough rewrite.

This is supposed to be a public window into Aalto and its CS Department. Small "superficial" things matter. (This is not intended as a slight towards whoever wrote the texts. It's just that we collectively need to do a lot better on these things.)

**Comment by PasiSa** [comment]
This is addressed by Ella's recent work
