### ISSUE TITLE
LTI: expose globally unique username (usermodel username) in LTI parameters (e.g. user_id)

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#420]
Goal: use should be able to login to supporting service directly using e.g. HAKA, but also from A+. We need to be able to link these two methods to same user in the supporting service. To do this, A+ needs to share HAKA identity in LTI launch.

It's unclear if `user_id` should be used for this or a custom LTI parameter. As service should use combination of LTI instance name and user_id for unique user identifier, a custom logic is required for both options (LTI service needs to trust that `user_id` is unique or read the custom parameter).

Other option is to use email for looking up existing users (again, needs to be globally unique.

**Comment by Mankro** [comment]
I have a feeling that only email address can be trusted to be globally unique. AFAIK, the LTI standard does not suggest that usernames should/could be used in the way Jaakko described, thus no external system could really trust the value to be unique. Furthermore, adding any custom LTI parameters implies that the implementation does not work with any external ("not within our control") system that just follows the standard.

My gut feeling also says that many other LTI Tool Providers already use the email address for connecting LTI users to other normal user accounts.

**Comment by raphendyr** [comment]
> My gut feeling also says that many other LTI Tool Providers already use the email address for connecting LTI users to other normal user accounts.

Downside of that is that the system _must_ ensure the email can not be changed. I.e., the email _must_ be unique and trusted sources (e.g. HAKA) must overwrite existing emails (I think we now link based on that). In addition, there can't be way to manually create a user with email in restricted domain, e.g., user's created manually or via google, can't have aalto.fi domain in our installation.

It's true that the username should be used in combination of `(user_id, tool_consumer_instance_guid)`, which would ensure that different users from multiple tool consumers would have unique usernames.

It's possible that we can't user LTI for logging in to a system, where we also provide logging in via Shibboleth as there is no _strong_ methods of linking identities and there is high risk of creating mistakes.

Further I have thought a bout this, I think apluslms should move shibboleth to a microservice, which can provide identification to multiple services in the cluster. Logging in to a another microservice would then forward the authentication to the identity provider microservice, which would include the cached login.

That said, I think this issue should be closed in favour of a more secure solution.
