### ISSUE TITLE
A+ front page

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#425]
The A+ front page should display the name of the course instance in addition to the course name and code; Multiple instances of the same course are hard to separate in the A+ front page because the only different parts are the open/close dates and the image. Course instances have names, so that should be displayed in the front page too. Jaakko has some ideas; contact him!

**Comment by Mankro** [comment]
Juha suggested that it would be nice if courses stayed on the front page somewhat longer than they are open. Students and teachers still frequently visit a course one or two months after it has ended, to check grades and for other reasons.

**Comment by raphendyr** [comment]
I had ideas that the front page could have search and filters, so e.g., FiTech student could easily find courses that are available. In addition, we could create page for courses (404 now), whcih would list all  instances, shoiwng the active and future in addition past intances.

**Comment by raphendyr** [comment]
Also this issue seems to be related #11

**Comment by saarasat** [comment]
This issue will focus on:
1. adding the instance name to the module-box on Front page.  
2. Dividing the front page into two sections for students and staff:
- In the upper section there should be all the courses the student is currently enrolled in OR a staff member (assistant/teacher) is currently teaching. These should show 1 month after the set ending time.
- In the bottom section there should be all the currently ongoing courses regardless whether student has enrolled in them or not. These will have the same cut-off point timewise as now, thus only currently active are showing.

The ideas about filters, search and page for different instances will continue on to separate issue after this one has been closed.
