### ISSUE TITLE
Lightboxes are rendered behind Storyline presentations in the O1 course (NB. opening feedback notifications)

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#430]
Fixing CSS z-index rules for the right elements should be enough.

**Comment by raphendyr** [comment]
This issue doesn't seem to be a problem anymore. Screenshot from production A+ from the place this should be a problem:

![image](https://user-images.githubusercontent.com/2327687/83501904-7f56d400-a4c9-11ea-86d3-c7bb90c0dfae.png)
