### ISSUE TITLE
LTI: limit use of SHA1 hash, as it's not secure anymore

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#435]
This requires support from tool producers too, so we need option to support old unsecure services. Anonymous data could be required for unsecure connections.

Blocked by #436, i.e. support newer interface with higher security

**Comment by Mankro** [comment]
LTI 1.1 protocol specifies SHA1 hash, so you can't just change it. Backwards compatibility doesn't leave any room for changing the specs, but some day we could support LTI 1.3 that has better security. This isn't relevant yet in 2020, though.

**Comment by annirytkonen** [comment]
is this relevant anymore? I would close this. LTI 1.3 is under construction and likely we don't want to support old unsecure services.

**Comment by Mankro** [comment]
Sure, let's close this one. LTI v1.0 specs require the weak SHA-1 hash. It is required for LTI services that don't support LTI v1.3.
