### ISSUE TITLE
Support for different model answer visibilities needed

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#453]
Currently: if model file is provided, it will be visible to teacher and assistants and for students after DL. 

INSTEAD, It should be: 1) if model file is provided, it will be visible to teacher and assistants always, 2) option to select when model is visible to students, if at all, 3) options should allow: never, after DL, after module/round, after date time. 

To support different times/visibilities, we could include the information in model url as a string. This would support multiple models for assistants and one for students. Tehtävän voi konffata niin, että vaikka sillä on malliratkaisu, ratkaisua ei julkaista kurssin normaalin linjan mukaisesti DL:n jälkeen, vaan ratkaisun paikalla näytetään opettajan rst:ssä konffaama teksti. (Tämä tulisi varmaan käyttöön vapaaehtoisille lisätehtäville joiden malliratkaisuja ei haluta näkyviin. Joillakin ei myöskään ehkä ole malliratkaisua, mutta se on sitten eri juttu.)

**Comment by Mankro** [comment]
Changing the time when the model answers are revealed was added as a new feature in #880.

* https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/exercise/exercise_models.py#L520
* https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/exercise/reveal_models.py#L12

> Tehtävän voi konffata niin, että vaikka sillä on malliratkaisu, ratkaisua ei julkaista kurssin normaalin linjan mukaisesti DL:n jälkeen, vaan ratkaisun paikalla näytetään opettajan rst:ssä konffaama teksti. (Tämä tulisi varmaan käyttöön vapaaehtoisille lisätehtäville joiden malliratkaisuja ei haluta näkyviin. Joillakin ei myöskään ehkä ole malliratkaisua, mutta se on sitten eri juttu.)

This hasn't been implemented: not showing the model solution but some message configured in RST instead.
There is a workaround for this: configure a text file as the model solution and write the message there without showing a real solution to the assignment.
