### ISSUE TITLE
Teacher: need for filtering student JUTUT-feedback

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#455]
opettajalle mahdollisuus selata niiden kurssilaisten palautteita kurssin varrelta, jotka lopulta keskeyttivät (viikolla N) (toteutus tageilla = lisätään tägi "keskeyttänyt")

**Comment by raphendyr** [comment]
Currently, teacher is able to create a tag `dropped` for example, to indicate that a student has left the course. A+ doesn't include way to drop or leave courses, and that would be too much work for now. Thus, only thing to do now, would be informing teacher how they can solve the use case with a bit of manual work (using a tag).
