### ISSUE TITLE
Download all submissions to an exercise (the best submission of each student or all of them)

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#459]
There is already a script for downloading submissions from the A+ API, but it would be easier for the teacher if submissions could be downloaded directly from the A+ UI.

**Comment by Mankro** [comment]
@alalav1 could work on this after current tasks. Say something here when you are ready to start.

**Comment by alalav1** [comment]
How should I proceed? Where in the UI should the button be? What does download mean in this context: to show all the submissions in the browser or actually download those exercises to the user's pc? What format should they use? @Mankro

**Comment by Mankro** [comment]
Let's not work on this until we have a real usecase for this feature. Submission data and files can be already downloaded from the API.

**Comment by Mankro** [comment]
Duplicate issue https://github.com/apluslms/a-plus/issues/586
