### ISSUE TITLE
Enrollment exercise should not use the module open and close times

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#462]
Only the enrollment open and close times from the course settings should be effective for enrolling in the course. It works like that when there is no enrollment exercise and the student only presses the enrollment button. If there is an enrollment exercise, then currently the module open and close times interfere with it and causes confusion when the module close time is different from the course enrollment close time.

**Comment by alalav1** [comment]
I will soon start to investigate this.

**Comment by alalav1** [comment]
#465 This PR focuses on enrollments after the module closing time.

**Comment by Mankro** [comment]
We decided that it is feasible to only fix module close times so that enrollment exercises are not affected by module close times. Module open times are checked in the CourseModulePermission and it has no knowledge of the exercise that is being opened so we can not separate enrollment exercises from normal exercises there. It is more typical that the course module closes before the course enrollment and that is fixed in the PR #465.

https://github.com/apluslms/a-plus/blob/014cc62e18f63e45d3c0192e23567b1fe37d27a4/course/permissions.py#L127

**Comment by Mankro** [comment]
#465 was merged and that fixes the module close times concerning enrollment exercises. I am closing this issue now since we decided that we can't fix module opening times affecting enrollment exercises.
