### ISSUE TITLE
Teacher should be able to manually enrol students in the course

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#467]
Sometimes teachers need to manually add students to the course after the normal enrollment period has ended. The student can not enroll in the A+ course himself/herself at that point since A+ does not allow it.

There could be a new subpage in the A+ course participants section. It would have a form in which the teacher could select students to enroll in the course. The teacher would search for students with their names or student IDs. This manual enrollment could always be done by the teacher even outside the course enrollment open and close times.

**Comment by jsorva** [comment]
N.B. When addressing this, it's important to consider the issue of background questionnaires (which some courses require students to fill in upon enrolling).

**Comment by Mankro** [comment]
@jsorva I would say that the enrollment questionnaire is skipped and ignored if the teacher manually enrolls a student afterwards. Otherwise, the implementation would become awkward and complicated. This feature is only intended to be used in rare cases when the student must be added to the course after the normal enrollment period. I would keep this implementation very simple.

**Comment by Mankro** [comment]
@alalav1 started to work on this.

**Comment by Mankro** [comment]
Duplicate enrollments may become a bigger issue when teachers can enroll students manually: #512.
