### ISSUE TITLE
Need an efficient way to search for data in fields.

### ISSUE THREAD

**Issue by alalav1** [apluslms/a-plus#476]
Current version downloads thousands of users in the HTML template. For example the edit course page is very slow due to the HTML template containing data of 14000+ A-plus accounts. There should be a way to search students without populating the template. The users could be searched using AJAX and JavaScript from API which already contains all the information needed.
The pull request #469 needs this issue solved to be continued.

**Comment by Mankro** [comment]
PR https://github.com/apluslms/a-plus/pull/479

**Comment by Mankro** [comment]
Pull requests #479 and #515 have been merged. I fixed a lot of code after the PRs in commits from https://github.com/apluslms/a-plus/commit/c5741ce44f8248056000ed4d56c1b7eb47ca3b65 to https://github.com/apluslms/a-plus/commit/5351362b40bb03693d0f0d16c79926eec92e4962. The AJAX search feature is now stable and mature enough that this issue can be closed.
