### ISSUE TITLE
Investigate the possibility to add Astra plugin to the Moodle plugins directory

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#484]
The possibility to add Astra to the official Moodle plugins directory should be investigated. "Additional users" would take A+ to use via Astra, if the plugin were available via the plugins directory. The plugin validation process can be found here: https://docs.moodle.org/dev/Plugin_validation. 

If it turns out that it is meaningful to validate Astra, then this issue should be split to/followed by implementation issues, and at that point we should re-discuss the workload, priority, schedule and assignee(s). Additionally, instructions on how to use the plugin, should be written.

**Comment by Mankro** [comment]
Closing. This issue is moved to the Astra repository: https://github.com/Aalto-LeTech/moodle-mod_astra/issues/2
