### ISSUE TITLE
Download exercise template files

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#485]
> **Migrated from Trello**

In A+, the exercise template files (e.g., skeleton code for the student in a programming exercise) functionality currently only shows the content of the files in a modal dialog. The user may not directly download the file. A+ should enable users to download the files too instead of just copy-pasting from the modal dialog.

The modal could, for example, have a download button that downloads the actual file to the student's computer. This download URL could use some GET query parameter (?download=yes) so that the URL is almost the same as what is used for the current modal.

---
**Comments**
>**Jaakko Kantojärvi:**
As extra, add a feature to download all template files as a zip (tar.gz can be created in memory, maybe zips can be created too)

>**Jaakko Kantojärvi:**
The modal could, for example, have a download button that downloads the actual file to the student's computer. This download URL could use some GET query parameter `(?download=yes)` so that the URL is almost the same as what is used for the current modal.

**Comment by Mankro** [comment]
Closing this issue because the newer #894 includes this as well.
