### ISSUE TITLE
The domain of the student number must be saved with the number

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#505]
> **Migrated from Trello**

This is needed in order to properly support the HAKA federation login in A+.

Currently, student numbers are saved in user profiles without their domains, such as aalto.fi. However, the same student number may be used in multiple institutions, so the domain of the student number must be saved with it. When the student number is used in the UI or API, it should also take the domain into account.

This also means that the current logic of separating internal and external users must be changed. Currently, external users log in via Google, but when HAKA is opened, external users may also use HAKA from an external university. (That is, not all HAKA users are internal.)

---

**Conversation**

>**Markku Riekkinen**
Idea for a quick fix from Jaakko (in Finnish):
jos tehään niin että shibboletista parsitaan kaikki opiskelijanumerot (domain + numero) ja asetuksiin "internal" domain. Sit laitetaan kantaan op num jos on vastaavan domainin opsikelijanumero, muuten roskiin. Sit external user on jos ei oo opiskelijanuneroa. Tää jättää joukon opettajia jotka on sit external mutta sen ei pitäis haitata mitenkään. Jos lisää dummy op numeron niin saa ulkoisesta tyypiatä sisäisen

>**Markku Riekkinen**
It looks like we must be able to support more extensive course visibility configuration than just internal/external users. This makes things more complicated. For example, we need courses that allow internal users and users from certain HAKA institutions (they are external but not all external users in the world are allowed).

>*Side note:* FiTech students will probably have Aalto accounts, so they would actually behave like normal internal students even though they are not normal Aalto degree students.

>**Jaakko Kantojärvi**
a critical part is now implemented in the PR https://github.com/apluslms/a-plus/pull/392 - we only take a student number from a configured domain and ignore rest.

>After user models are updated to support multiple domains, we can actually keep the domain with the student number.

>I drop the importance of this particular ticket

**Comment by Mankro** [comment]
Somewhat related to https://github.com/apluslms/a-plus/issues/413

**Comment by raphendyr** [comment]
The student number would need to be changed to a list of tuples `(domain, numer)`.

**Comment by Mankro** [comment]
Closing this issue since the new issue https://github.com/apluslms/a-plus/issues/788 replaced this one.
