### ISSUE TITLE
A+ should fix multilingual chapter links from the format Sphinx produces to built HTML files

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#509]
> **Migrated from Trello**

The PR https://github.com/apluslms/a-plus-rst-tools/pull/58 changed rst-tools so that the chapter links (web link from one chapter page to another) work in A+, but they do not work in the local filesystem (when files in the `_build` directory are opened in the web browser). This is because some URLs are rewritten in a way that the URL no longer refers to a real file in the filesystem. The link works in A+ because its format matches the format A+ uses after A+ has fixed URLs from its perspective.

A+ modifies the URLs in chapter contents here:
https://github.com/apluslms/a-plus/blob/master/lib/remote_page.py#L174
This code could be changed so that it can fix URLs somewhat in the same way as the fix in the rst-tools (pull https://github.com/apluslms/a-plus-rst-tools/pull/58) did. The fix in rst-tools must be changed/removed so that it does not break URLs in the local filesystem.

The URLs that particularly do not work in the local filesystem are the following:

* chapters in multilingual courses because the RST files should have language suffixes (`_en.rst`). RST-tools removes the language suffix from the link but the built HTML file has the suffix. Chapter URLs in A+ do not use the language suffixes.
* chapters in subdirectories under module directories. If a module directory has subdirectories (like this `module01/material/chapter.rst` instead of the typical `module01/chapter.rst`), then RST-tools replaces the slash directory separator with an underscore character. That URL works in A+ since A+ uses chapter keys in the URLs (instead of identical full directory paths used in the git repository). The underscore URL does not work in the local filesystem since Sphinx builds directories to the `_build` directory in the same structure that they exist in the RST source and URLs become broken for that case when the `/` becomes `_`.

---
**Comments**

>**Markku Riekkinen**
**@Juha_Sorva** This is the card about the URL issues in the local `_build` directory. As you said, you regularly open files directly under the _build directory instead of running Docker A+ containers in your laptop.

**Comment by Mankro** [comment]
I think these PRs are intended to fix this issue:

* https://github.com/apluslms/a-plus/pull/463
* https://github.com/Aalto-LeTech/a-plus-rst-tools/pull/65

**Comment by Mankro** [comment]
The fix required changes in a-plus and a-plus-rst-tools:
* https://github.com/apluslms/a-plus/commit/ee9e9060c0bf3d8f2202464ef3560cb242110025
* https://github.com/apluslms/a-plus-rst-tools/commit/1e41a8b04cf5c849e38b54ae9196a429d77fde37
