### ISSUE TITLE
Student is able to enroll on a course multiple times

### ISSUE THREAD

**Issue by oseppala** [apluslms/a-plus#512]
A student can in some cases enroll on the course multiple times. An example can be found in the WSD 2019-2020 course on the Aalto production server.

Parts of the system which are or might be affected (mark if fixed or checked to be not affected):
- [ ] API / student points: `/api/v2/courses/<course_id>/points/<user_id>/`

**Comment by raphendyr** [comment]
Problem:
* Enrollment model doesn't enforce unique pair of course and user. Code first check if there exists a enrollment, if not, it creates one in [course/models.py](https://github.com/apluslms/a-plus/blob/master/course/models.py#L522) using django `get_or_create`, which is [not atomic](https://github.com/django/django/blob/master/django/db/models/query.py#L559).

How to fix:
* Add unique constraint to Enrollment model (course, user) -pair.
* Create migration to merge duplicates to a single enrollment in the existing database

**Comment by raphendyr** [comment]
I raise the priority, as it seems be affecting two Universities.

**Comment by Mankro** [comment]
We got a report that double enrollments possibly cause a crash (HTTP 500) in the API: `/api/v2/courses/COURSEID/points/ID/`

I feel like increasing the priority even further.
