### ISSUE TITLE
In A+ it should be possible to set student's default language in a specific course

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#518]
> **Migrated from Trello**

- [x] Add language to the userprofile - #617
- [ ] When user is viewing material with different language, make it clear that it's not their default, e.g., show a warning.

    Additionally, buttons (links) should be shown to set that language as their preferred language (to enrollment object) and to switch back to their preferred language.

    This is more about the language set via url (query parameter), so that when the user is directed to a material in a different language than in their enrollment object (or profile), then that would be pointed out to them.

- [x] Store language in the Enrollment object. Think about the case where system has 3 languages sv, en, and fi, user has set the language in profile to sv and course is provided in en and fi. In that case, A+ should be able to remember the language the user likes to read that course and not force to set profile language. - #632

----
**Comments**

>**Jaakko Kantojärvi:**
At least for a profile, so when student logs in, the language is returned to original one.

**Comment by Mankro** [comment]
The UserProfile already has a `lang` field: https://github.com/apluslms/a-plus/blob/d34f94b7c9a8e4d22cd28d08968b36787bb344c4/userprofile/models.py#L37-L38
Is it used anywhere? 

Like the issue says, when the student comes to a multilingual course, the course should be by default displayed in the language set in the userprofile. It would be good to check which language is now used in the old code. Is it random, or is it based on the HTTP language headers?

If the user views the course in other language than what is set in the profile, we need to careful about making too obnoxious warnings about it. If the user really wants to view the other language, then they should not be constantly bombarded with warnings about the language not being their default.

This issue can be done after https://github.com/apluslms/a-plus/issues/520 (different language URLs for multilingual courses).

**Comment by raphendyr** [comment]
> It would be good to check which language is now used in the old code. Is it random, or is it based on the HTTP language headers?

Django session (or actually a separate cookie) contains the language information. It's initialized with the HTTP language. I didn't remember we had DB reservation for the language, but I don't think it is used yet at all.

Current behavriour is that the user can have multiple sessions with different languages. We should replace this with the user linked language. The language selection in profile page would make more sense then.

**Comment by veeraalt** [comment]
> This issue can be done after #520 (different language URLs for multilingual courses).

I think this issue needs to be done before #520 because #520 affects how the language is selected, and now the language is stored in the wrong place (in a cookie). The lang field in UserProfile is not in use now, so it would make sense to fix this first.

**Comment by Mankro** [comment]
> > This issue can be done after #520 (different language URLs for multilingual courses).
> 
> I think this issue needs to be done before #520 because #520 affects how the language is selected, and now the language is stored in the wrong place (in a cookie). The lang field in UserProfile is not in use now, so it would make sense to fix this first.

Alright, good point!
