### ISSUE TITLE
Students shouldn't get (an obscure) error message for attempting to access the solution of an assignment they've submitted in a different language

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#519]
> **Migrated from Trello**

**Comment by Mankro** [comment]
We are not able to replicate this issue anymore, so we close the issue.

Some details from 2018 when there seemed to be a real bug:
If memory serves, there is/was an issue with 1) doing an assignment (submit directive in RST) in Language A; 2) switching language to B at some later point of time; 3) going back to check the model solution while language B is active.
