### ISSUE TITLE
Show pseudonymized names in UI

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#533]
>**Migrated from Trello**

* anonymous mode - render all student names with the nickname (allows showing real stuff in public setting)
* random gravatar image

**Comment by Mankro** [comment]
> where does this need come from - what is the use case? Sounds like it is not in course/teaching context. I'll close this one for now.

The use case is to show demos of A+ to anyone who shouldn't otherwise see the real students' personal data.

**Comment by oseppala** [comment]
Use cases:
1) Development: issue screenshots
2) Lecture use: when A-plus is used during lectures, student names should not show
3) Onboarding new users
4) Anonymous reviews by TAs
5) Manuals, presentations

Implementation could be done to a large extent with either
a) a simple django template filter that **pseudonymizes** the data
b) database manager / custom user that **pseudonymizes** already what you get from database
c) tagging names/student numbers with css class + custom css that **hides** the info (less secure, but this would anyway run in the UI of someone that should see that data)
d) tagging data and running any existing JS pseudonymization library on that.

The on/off - variable would be placed in session, so none of these require database changes. Pseudonymization would be superior to anonymization

**Comment by PasiSa** [comment]
Otto makes good points above. There could certainly be uses for this.
