### ISSUE TITLE
New feature: results page tick box for omitting course personnel

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#540]
feature request: There could be a tick box (on by default) omitting course personnel from the list (even though they have ”enrolled”).

(The current situation: The A+ all results page includes teaching assistants if they have enrolled in the A+ course. There is no filter to hide/remove the assistants from the results. You can remove them manually in Excel after exporting the spreadsheet file from A+.)

**Comment by Mankro** [comment]
This issue depends on the issue https://github.com/apluslms/a-plus/issues/602.

**Comment by Mankro** [comment]
#602 (and related PRs) fixed this. Teachers and assistants are completely excluded in the All results table. There is no way for including them, but I don't think that's needed.
