### ISSUE TITLE
Sisu integration (course start)

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#550]
automatic enrollment of students to A+ courses based on course registration in Sisu.

Teacher needs spring 2020: nr 1.

**Comment by Mankro** [comment]
Automatic synchronization of enrollments would probably benefit from a better enrollment model. Adding user roles to enrollments is another issue: https://github.com/apluslms/a-plus/issues/602

**Comment by PasiSa** [comment]
I accidentally created a new issue for this, so closing this older version
