### ISSUE TITLE
Provide a link to skip over the navigation

### ISSUE THREAD

**Issue by mtthwhggns** [apluslms/a-plus#559]
When navigating with the keyboard, users currently must tab through the brand link, the "select course" list, and profile link before reaching the page-specific content. After that, the course pages have a further menu which is present on every page. 

Criterion 2.4.1 of WCAG 2.1 (included in level A, the most basic) (https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks) requires that:

> A mechanism is available to bypass blocks of content that are repeated on multiple Web pages.

Most websites achieve this with [a link that's hidden until you tab into it](https://www.w3.org/WAI/WCAG21/Techniques/general/G1). At this point, it becomes visible. Clicking it jumps to the page content. Here's GitHub's example:

![GitHub skip link](https://user-images.githubusercontent.com/6674046/84235060-e7c33800-aafd-11ea-80be-35a06c1db945.png)

After activating it, focus is ready to enter the link "apluslms" visible in this screenshot - it has bypassed the whole top bar.

There's one which works exactly the same on Aalto.fi:

![Aalto.fi skip link](https://user-images.githubusercontent.com/6674046/84235658-e3e3e580-aafe-11ea-83c4-c1d2e04fbc3a.png)

I'd approach this with a similar link at the top of all pages, which is hidden by default. Activating the link takes focus to the first item after the top bar. I'd then consider a second link to skip the course navigation, which is only visible in the course navigation. This needs more testing though.

I'd not anticipate these will be noticed by users not using the keyboard to navigate. Users who navigate using the keyboard (whether related to disability or preference) probably see these everywhere and are used to them. 

The meta issue: #501

**Comment by Mankro** [comment]
A very clear description. Your suggestion for the fix sounds good! :+1:

**Comment by raphendyr** [comment]
> I'd not anticipate these will be noticed by users not using the keyboard to navigate.

I would agree. I didn't know this cool feature existed in the example sites. :+1:
