### ISSUE TITLE
RST is clumsy as source language --> additional documentation needed

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#562]
Issue collected from Aalto teachers spring 2020: https://wiki.aalto.fi/display/EDIT/Teacher+needs+spring+2020

Plan A: Jhosimar is writing new instructions in the aplus-manual that could ease the pain of writing RST a little bit. There are some hotkeys or macros in the VS code editor that could help.

Plan B: use (pilot) LaRST (Latex-to-RST), which was implemented by Tomi Janhunen at Tampere University. It compiles Latex into the RST format used by a-plus-rst-tools. The special A+ features, such as exercises, are defined with custom Latex macros/environments. Tomi has not yet released the project openly, but the project should be close to finished. One should consider if LaRST supports enough A+ features to be useful or is something crucial still missing. --> there has not been interest in Aalto on LaRST, though it has been presented in webinars.

**Comment by annirytkonen** [comment]
instructions are available and Aalto teachers have not been interested in LaRST. So I'll close this one.
