### ISSUE TITLE
Opportunity to choose which rounds are used in calculating the grade (extra rounds can replace normal rounds)

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#567]
Issue collected from Aalto teachers in spring 2020, https://wiki.aalto.fi/display/EDIT/Teacher+needs+spring+2020

Currently, A+ does not have a feature for computing the grade for exercises (except there is one limited and hidden feature for just that). Some courses use a JavaScript-based grade calculator that only shows the estimated grade for exercises in the student's UI. 

In Y1, studetns have the opportunity to do extra rounds if the normal rounds are missed e.g. because of sickleave. The course includes 9 rounds, and the student can replace normal rounds with extra rounds with certain rules. 

Counting the grades will be included at Aalto level in the SAM process in Salesforce. Is this feature needed in A+ or in Salesforce, and is this needed for the teacher or for the student?

**Comment by annirytkonen** [comment]
this will either be implemented in SAM, in simple form, or, in complex cases, teachers will count the grades their own ways.
