### ISSUE TITLE
Course-page containing all the instances of a course

### ISSUE THREAD

**Issue by saarasat** [apluslms/a-plus#578]
Currently there is no list of the instances of the same course. A page collecting these different instances would needed, as discussed in https://github.com/apluslms/a-plus/issues/425

The page should contain the past, current and future instances of the same course. 

Details about the style, navigation and possible limitations by user-type (teacher, student, assistant) can be discussed here. 

This old issue is related https://github.com/apluslms/a-plus/issues/11

**Comment by raphendyr** [comment]
> O1 needs

The specific Programming 1 need is the ability to link to the newest version of the course. See the part about query string `?code=cs-a1110&when=current&next=/foo/bar&forward=true` in #522

**Comment by Mankro** [comment]
When/if this issue is taken under development, it is important to think carefully of the use cases and URLs. There are different ways to organize the URLs for the list of course instances and linking to the latest instance.

From #746:

> Perhaps there could be one URL for the list of instances (e.g., plus.cs.aalto.fi/o1) and another for the most recent instance (e.g., plus.cs.aalto.fi/o1/current).
>
> Alternatively plus.cs.aalto.fi/o1 for the recent instance and plus.cs.aalto.fi/o1/instances or similar for the list.
