### ISSUE TITLE
The grading language can not be set in the API submission endpoint

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#581]
New submissions for grading can be sent to the API via the endpoint `/api/v2/exercises/ID/submissions/submit/`. The language can not be set via the API. The language affects the grading since it is one of the parameters sent to the grader in the A+ grader protocol. The API must be changed so that it accepts an optional language parameter and uses it in the grader protocol. If no language is given to the API, then it uses the (course) default language like it seems to do now.

The name of the POST parameter for the language in the API could be `__lang`. Underscores try to avoid collisions with real parameters used by exercises. We need to think how this relates to the existing hacky submission data parameter `__grader_lang` or should we use that one for this case as well.

Edit: see the discussion for better ideas about the parameter names.

A+ API code:
submit endpoint: https://github.com/apluslms/a-plus/blob/cd0cfb593656340dbcdab9078a7781d0d96599cd/exercise/api/views.py#L235
grade function: https://github.com/apluslms/a-plus/blob/cd0cfb593656340dbcdab9078a7781d0d96599cd/exercise/exercise_models.py#L693
language is taken from the Django settings, but the language can not be set via the API yet: https://github.com/apluslms/a-plus/blob/cd0cfb593656340dbcdab9078a7781d0d96599cd/exercise/exercise_models.py#L697

**Comment by raphendyr** [comment]
Typically, it wouldn't be a good idea to mix varibles from multiple namespaces to one. For example, query parameter or a HTTP header could be uses to have separate namespace.

However, the language parameter is important definition about the submission, thus it makes sense for it to part of the submission namespace. I have been thinking that we should reserve a namespace for A+/grader values. For example, `__aplus__`, which would include a json string with the actual values. For example, `__aplus__={"lang": "en"}`. 

If the language parameter is part of the form namespace, then that field should be annotated someway in the form schema.

p.s. `__grader_lang` shouldn't be used. It was just a fast hack to fix questionnaires in context where the protocol doesn't have a good support for that. Here, we would like to inform A+ about the language, so it can forward that information to the grader. This language probably should be stored with the submission, so resubmission or a background task can forward it.

**Comment by Mankro** [comment]
Good points from @raphendyr . So if I understand correctly, we still want to save the language in the submission data of the submission record in the database. We shall use the `__aplus__` key with the JSON value like raphendyr suggested.

**Comment by Mankro** [comment]
The linked PR #588 was merged to the hotfix branch `for-o1-2020` that will be merged to master after the summer.
