### ISSUE TITLE
Unclear link purpose on course results page

### ISSUE THREAD

**Issue by mtthwhggns** [apluslms/a-plus#597]
There's some background here: https://apluslms.github.io/accessibility-audit/patterns/fixable-a/link-purpose/#examples

~~@etanttila can you take a quick look and tell me if you think you can take care of this alongside your other points page work?~~

I was mistaken, @etanttila 's issue doesn't share any components with this page.

**Comment by Mankro** [comment]
I suppose this issue refers to the "exercise results" page that all students see in a course, not the teacher's "all results" (course points) page.

The "exercise results" page indeed has a submissions column (in each module) that has badges with the submission counters like "1 / 10". The badge is an `<a>` element, but it is not a link. It toggles the submission dropdown menu.

Would the correct solution be to add the attribute `role="button"` to the `<a class="dropdown-toggle" data-toggle="dropdown">` element that triggers the submission dropdown menu?

**Comment by jaguarfi** [comment]
I think that should solve the problem.
