### ISSUE TITLE
Review the consistent use of links vs. buttons

### ISSUE THREAD

**Issue by mtthwhggns** [apluslms/a-plus#598]
Two parts here:

## Link vs. Button

This is explored in more detail in [the audit report](https://apluslms.github.io/accessibility-audit/patterns/fixable-a/links-and-buttons/). 

We should only use buttons for things that behave like buttons, and links for things which behave like links. It might not be possible to find every example, but as a task, it might involve going through those already identified and switching them over. 

Perhaps this can be added to our quick accessibility check process for PRs. 

## ~~Consistency~~

~~As highlighted in #585 , we have some inconsistent use of button colours.~~

~~We have some cases where we use colours which have a functional or semantic meaning because we want different colours. One example might be the "danger red" 'Login using Google' button.~~

~~Since we shouldn't rely on colour to make differences between things clear, (WCAG 1.4.1) One idea would be that we have a single style of button, and replace all buttons with this style. Perhaps we have a second style for "destructive" actions (delete).~~

~~I'll give some thought to the right way to approach this and add a new comment to this issue soon.~~

Moved to #601

**Comment by Mankro** [comment]
Highlight from the audit report (at least this must be fixed soon):

## Course Index

On the course index page, when the recent results are shown, there is something that appears to be a text link, labelled as:

    Show older assignments.

This is marked up as a link, but changes the content of the current page. Users may expect to be taken to a different page, instead the content of this pages with no clear indication.

If this were labelled as a button, it would give a much clear indication that “clicking this does something”. There could also be benefits to users not using assistive technology to acheive a highler level of consistency in how interface elements are used.

**Comment by skulonen** [comment]
@Mankro The "show older assignments" link has been converted to a button, see commit https://github.com/apluslms/a-plus/commit/6bd9e72523ded8eb2926adbc943a5957de533dd8. As far as I understand, the aria role "button" is not necessary since I used a `<button>` tag.

**Comment by Mankro** [comment]
That is correct, the button element has the correct ARIA role by default. Thanks!
