### ISSUE TITLE
Increase font size, improve readability and make a better use of font sizes in general.

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#609]
Currently A+ use a `font-size: 14px` and it makes it difficult to read the text in small devices. Of course, we can make use of the zoom but increasing the base font might be beneficial. 
https://css-tricks.com/accessible-font-sizing-explained/

Depends on #594

**Comment by mtthwhggns** [comment]
Strongly agree that this would be good.

Since we rely so much on Bootstrap at the moment, I'd suggest this be checked after https://github.com/apluslms/a-plus/issues/594, as it will be much easier to change on top of that.

**Comment by Mankro** [comment]
Sounds good! Let's do this during the summer when the time is right concerning related issues.
