### ISSUE TITLE
Add deviations to the points cache

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#624]
Makes it possible to add deviationed information to the API for example. Any case, to use deviation information well, the information should be available easily (i.e. via cache).

Related issues:
* Add devitaions to the UI: #529

For reference see:
* https://github.com/apluslms/a-plus/issues/605#issuecomment-656071888

**Comment by Mankro** [comment]
The points cache was changed in the delayed feedback feature and it now contains some personal deviations. But we should check if it is adequate for using the deviations in the student's UI.

* https://github.com/apluslms/a-plus/issues/882#issuecomment-947856430
* https://github.com/apluslms/a-plus/pull/880
* https://github.com/apluslms/a-plus/pull/890
