### ISSUE TITLE
Drop line number from translation files.

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#676]
I think it might make future pull-requests easier if they wouldn't update the changed line numbers. I don't personally see much benefit for the line numbers (or much for file filenames either, but those change rarely).

We could run `./manage.py makemessages --ignore='venv*/*' --no-obsolete --add-location file`, which would use only file name, not line number in the po comments.

The option `--add-location file` is described here: 
https://docs.djangoproject.com/en/2.2/ref/django-admin/#cmdoption-makemessages-add-location

- [x] Document the change in `doc/` (done in commit https://github.com/apluslms/a-plus/commit/2071a580d269ecfdfd213fe0c10800df492eab02)
- [ ] Update translation files, when there isn't too many pull-requests open
  * done in a-plus (https://github.com/apluslms/a-plus/commit/f1c7758e3a7480f9ccaa4b0469b9035496da3bb5)
  * MOOC-Grader must be upgraded to Django 2.2 before this can be done (2.0 is the minimum, but we want 2.2 LTS).

**Comment by Mankro** [comment]
Sure, why not. The line numbers add a lot of noise to git diff.

**Comment by Mankro** [comment]
The `-add-location file` option requires Django 2.0 or newer, thus this operation can not be done in the MOOC-Grader yet.

https://docs.djangoproject.com/en/2.0/ref/django-admin/#cmdoption-makemessages-add-location
