### ISSUE TITLE
Adding student taggings in the participants page breaks after sorting any column

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#682]
Adding taggings to students does not work if you have sorted the participants page by any column. Adding works after reloading the page if you don't sort any columns.

**Comment by Mankro** [comment]
Your video shows very few users. What if there are much more users and their order also changes when you sort by different columns?

**Comment by EerikSaksi** [comment]
I had a look at this problem again and still couldn't reproduce. @jsorva if possible could you screen record the bug occuring so that I could try copy your exact environment and steps?

**Comment by Mankro** [comment]
@EerikSaksi the bug described in this issue has indeed disappeared at some point. I am also unable to reproduce it. It works now. I don't know when exactly this bug got resolved, but I know it was a real bug when this was reported.

However, there is a new bug now. It is not possible to remove taggings from a student. When you click a tagging, the small popup has a remove button. Clicking the remove button does not seem to do anything at the moment. You can see the remove button in your video: 
https://user-images.githubusercontent.com/46625399/206167206-8c8bcc69-d4c2-4c61-878c-bf6585bb1f04.mp4
