### ISSUE TITLE
Submission times should be displayed with more accuracy

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#685]
Submission times should be displayed with seconds, not only minutes. This is important for at least teachers when they compare submissions that were sent almost at the same time. Thus, at least the inspect submission page should use more accurate times if we don't want to use them everywhere. For example, the seconds are important when a student submits twice at **"17:49"**. The more accurate submission times could be **"17:49:01"** and **"17:49:02"** OR **"17:49:01"** and **"17:49:27"**. The teacher should see this difference easily.

Furthermore, the inspect submission should show the grading time in addition to the submission time.

**Comment by ttsirkia** [comment]
What is the exact use case for this? If we assume that the submissions are always ordered by submission time, why the second part is interesting?

**Comment by Mankro** [comment]
The seconds are needed to know if two submissions were submitted almost at the same time or if the submission times are almost a minute apart. Currently, the teacher can not see that. Students may claim that they consumed submissions by accident and the teacher needs to decide if the student is granted extra submissions.

Making two submissions at one time by double-clicking the submit button has been a problem in the past, though it has been fixed with a few lines of JavaScript.
https://github.com/apluslms/a-plus/blob/cd10e04963557444efeb11b06b2834bf47ace903/exercise/static/exercise/chapter.js#L850
