### ISSUE TITLE
Remove the user profile avatar icons from the student group menus

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/a-plus#698]
The user profile avatar icon was removed from the user profile page in #590. Now the profile icon needs to be removed from the student group menus that include it.

We decided to remove the avatar in order to remove the dependency on the external service gravatar.com and Wordpress accounts.

**Comment by Mankro** [comment]
The course participant page (for teachers) also shows the user profile avatar. The avatar should be removed from there as well.
