### ISSUE TITLE
Teacher should be able to change the teachers of the course

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#700]
Currently, only A+ admins may change the teachers of a course (model `Course` defines the teachers for all `CourseInstances` of the course). However, this has been an unnecessary hindrance that causes extra manual work and it is annoying to contact admins for such a trivial task. A teacher should be able to add and remove other teachers in the course himself/herself. It should be even possible to remove oneself as the teacher, after which one can no longer access the edit course page.

The edit course form already displays the teachers of the course. It can be changed so that the teachers are edited there. The assistants are already edited in the same form.

**Comment by Mankro** [comment]
Seppo is trying to fix this now.

**Comment by raphendyr** [comment]
I assume that the case "TA with teacher permissions removes the teacher" is not a responsibility of the app. E.g. that kind of case would be handled within the confains of the job contract. Therefore, all users with teacher permissions should always have a job contract, right?

I think, I made a mistake before and didn't consider that authorization and abuse could be handled more out side of the application. I just always put more pressure on the application it self. I think there might be a bit of similar reasoning on why mycourses is so strict on where teacher permissions come from.

**Comment by Mankro** [comment]
Yeah, if someone abuses their teacher role, the sysadmin can remove their access to the system. We should assume that the teachers trust each other or the assistants when they are given the teacher role in the system.
