### ISSUE TITLE
Favourited courses panel on startpage

### ISSUE THREAD

**Issue by ElektroVirus** [apluslms/a-plus#701]
When logged in, on the start page should be a list of favourited courses. Now when the user only has a few interesting courses, they need to search the list of all the courses. 
It would be nice if on top of the page were a short list of courses, which the user has favourited. This would speed up the navigation to  the course, the user was trying to get to. In the picture is an example, how the implementation could look like :)

Of course this favourite panel could only be shown, if a user is logged in. 

![plussa_favourite_courses](https://user-images.githubusercontent.com/33934600/97871754-940bf200-1d1d-11eb-986a-9e169623dbfa.png)

**Comment by ttsirkia** [comment]
Are favorite courses the same in which you have enrolled?

**Comment by ElektroVirus** [comment]
Well, it actually could be. My first idea was that the user manually favourites courses they wanted, but your suggestion sounds actually like a better idea since it creates less manual work for the user.

**Comment by ttsirkia** [comment]
It is also less work for the developers 😄

**Comment by ElektroVirus** [comment]
Well then it sounds it's the right solution :D

**Comment by ttsirkia** [comment]
Course staff members do not enroll (or they don't have to) but in DB level, it is know for which course you are part of staff and that could be used.

**Comment by ElektroVirus** [comment]
Ok. But for me it is also important, that also the courses I'm assistant in are listed in that favourites panel.

**Comment by raphendyr** [comment]
Does PR #608 implement what you are looking for?

**Comment by ElektroVirus** [comment]
Yes, that 'Minun kurssini' looks exactly what I want :)
So now I apparently must wait that TUNI updates their Plussa to that version.

**Comment by Mankro** [comment]
Closing the issue since the A+ v1.8 (December 2020) release will include a new feature that shows the user's enrolled courses in the frontpage.
