### ISSUE TITLE
Course JSON import should not leave unused empty hidden course modules to the course instance

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#719]
The aplus-json import leaves empty hidden modules if the module key does not exist in the JSON (anymore). Exercises are already deleted in this case (if the A+ exercise is not seen in the JSON *) so the module should be automatically deleted too if it becomes empty. Having many empty hidden modules in the course after importing is just frustrating and deleting them manually takes time.

*) if the exercise has submissions in A+, then A+ does not delete it, but leaves it in the hidden status.

**Comment by Mankro** [comment]
Related code: https://github.com/apluslms/a-plus/blob/56a16be7604f896258b6ca8dc81eea7d2dd2ae36/edit_course/operations/configure.py#L544

**Comment by skulonen** [comment]
> The aplus-json import leaves empty hidden modules if the module key does not exist in the JSON (anymore).

Does this mean that the module object still exists in the JSON, but its `key` attribute is missing? Just curious, why/when does this happen?

**Comment by Mankro** [comment]
The `key` should always exist. Like I wrote previously, "if the module key does not exist in the JSON". A+ may contain a module whose key does not exist in the JSON, usually because the course was imported once in the beginning, and then the keys were modified in the course git repo. The A+ course uses the old keys and the JSON contains other new keys when the course is imported again to A+. I don't want to leave empty hidden modules with the old keys after the new import.
