### ISSUE TITLE
Preview of ZIP files is broken

### ISSUE THREAD

**Issue by nikke234** [apluslms/a-plus#728]
Viewing the contents of a submitted ZIP file in A+ shows a garbled text representation of the binary data. This is a common source of confusion among students, as they want to check that they submitted the correct ZIP file, and get worried that something went wrong.

It would be nice if A+ would either render the contents of the ZIP in some way (e.g. show the directory structure), or show some "no preview for file" message instead.

**Comment by Mankro** [comment]
This has been fixed for PDF and ZIP files. A+ does not try to render them in plain text in the web page. Instead, the browser simply downloads the file.

The current implementation hardcodes a few common binary file types, which is not optimal:
https://github.com/apluslms/a-plus/blob/8811feab20862474ac69951ec04315a98e79c659/exercise/submission_models.py#L606
