### ISSUE TITLE
Unclear error message when submitting large files

### ISSUE THREAD

**Issue by nikke234** [apluslms/a-plus#729]
Not sure if this issue comes from A+ or one of the graders, but submitting a sufficiently large file results in a "communication error with the exercise" error. The error message in this case is pretty unclear.

**Comment by Mankro** [comment]
Related to https://github.com/apluslms/a-plus/issues/662

**Comment by Mankro** [comment]
This issue was duplicated here: https://github.com/apluslms/a-plus/issues/869
