### ISSUE TITLE
Download the list of submissions in a JSON format does not download a JSON file, it only open the JSON file in the browser

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#733]
The view submission button opens a modal with a dropdown menu that allows the user to **download** the submission in different formats.
![image](https://user-images.githubusercontent.com/10437475/100585090-ab76d480-32f5-11eb-9904-842236be07b2.png)

However, when the user selects the JSON format, the application opens the JSON file in the browser, but the expected behaviour is to download the actual `.json` file.

**Comment by Mankro** [comment]
This is easy to fix. The HTTP response needs to contain certain headers that trigger the browser's download dialog.

Example from https://stackoverflow.com/a/36394206:

```
import os
from django.conf import settings
from django.http import HttpResponse, Http404

def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404
```
