### ISSUE TITLE
The JavaScript for copying the hl language parameter copies some unwanted parameters too

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#745]
A+ has new JavaScript that copies GET query parameters from the current page's URL into links. The links are modified in the click event handler. This is intended for the `hl=en` parameter so that the same language is kept in the URLs and the pages do not change the language when you open links.

https://github.com/apluslms/a-plus/blob/57031587030092ac4c482fde53ff9d9577da0f0f/assets/js/aplus.js#L669-L689

However, there are cases when this behaviour causes issues. There are pages that depend on GET query parameters in the URL, but the parameters should not be copied to all link targets.

* When you are unauthenticated and you open a page that requires authentication, you are redirected to the login page. The URL includes the `next` query parameter so that you could be redirected back to the target page after logging in. However, the next parameter should not be copied to any link targets. If you open the front page from the top navbar from the login page, the `next` parameter stays in the URL for any link you open.

**Comment by Mankro** [comment]
Is there any better fix to this than to hardcode some parameter names in the JavaScript code? If the code never copies a query parameter called `next`, at least the login page would be fixed.

**Comment by jaguarfi** [comment]
I did not completely read the original issue that you wanted to solve with the PR that added this JS code. But maybe something like this may help.
https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#language-prefix-in-url-patterns
have you considered adding a sitemap? https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap

**Comment by jaguarfi** [comment]
That JS code also causes a problem with the modal windows. See PR #736

**Comment by jaguarfi** [comment]
One temporary solution could be to validate that the query includes only `?hr=**`

**Comment by Mankro** [comment]
https://github.com/apluslms/a-plus/pull/764 actually does not fix this issue.

**Comment by jaguarfi** [comment]
Yes, it is true. I forgot to add the validation to copy only the hl parameter.
