### ISSUE TITLE
External links are broken in SITEWIDE_ADVERT

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#749]
New A+ JS adds icons to links that open in new tabs. This breaks links in the SITEWIDE_ADVERT. The link text is not displayed correctly. 

The icon is added by this code: 
https://github.com/apluslms/a-plus/blob/57031587030092ac4c482fde53ff9d9577da0f0f/assets/js/aplus.js#L94-L119

**Comment by jaguarfi** [comment]
Broken How? can you attach a screenshot? or explain a bit more about the meaning of broken.

**Comment by jaguarfi** [comment]
I assume you are talking about the `SITEWIDE_ADVERT`
![image](https://user-images.githubusercontent.com/10437475/104476839-57842e80-55c9-11eb-9fdf-a4b9a84716ce.png)

The Javascript code did not break the `SITEWIDE_ADVERT`. The **course_base** template has its own `<span>`

```html
<span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
```

**Comment by jaguarfi** [comment]
@Mankro is it the site_advert broken in the **index.html** file? https://github.com/apluslms/a-plus/blob/57031587030092ac4c482fde53ff9d9577da0f0f/course/templates/course/index.html#L43

The card with the advert is not shown. It seems like the `class="advert-card"` is not working.

**Comment by Mankro** [comment]
Good points here. Yes, I meant SITEWIDE_ADVERT. I think the problem was not only that there are two "external link" icons (one of them existed before the new icon JavaScript like you said), but that the link would not work on clicking or the test would disappear. I don't remember exactly anymore, but I made this issue based on my testing.
