### ISSUE TITLE
Update deployment documentation about Django session settings

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#757]
We have investigated user session problems in the EXAM studio setup. A+ has had bad session settings for that use case. The deployment documentation, settings and examples should be updated. It is best to separate the normal and exam use cases since they require different things from the Django sessions. In EXAM, it is crucial that the sessions do not last longer than the exam lasts.

Copy of my notes:

We could start using the Memcached backend for sessions instead of the default database backend.
https://docs.djangoproject.com/en/2.2/topics/http/sessions/#using-cached-sessions
SESSION_ENGINE in local_settings.py (not in settings.py since it might not work in local development and testing).
https://docs.djangoproject.com/en/2.2/ref/settings/#session-engine 

At any rate, old sessions must be cleaned from the database. Table django_session has over 300000 rows.
https://docs.djangoproject.com/en/2.2/topics/http/sessions/#clearing-the-session-store 

EXAM A+ must use browser-length sessions. 
https://docs.djangoproject.com/en/2.2/topics/http/sessions/#browser-length-sessions-vs-persistent-sessions
https://docs.djangoproject.com/en/2.2/ref/settings/#session-expire-at-browser-close 
SESSION_EXPIRE_AT_BROWSER_CLOSE set to True in local_settings.py

Does the SESSION_COOKIE_AGE do anything with browser-length sessions? Probably not, but we don't use browser-length sessions in the normal A+ so this is still important.
https://docs.djangoproject.com/en/2.2/ref/settings/#session-cookie-age 

SESSION_COOKIE_SECURE must be set to True in local_settings.py (not in settings.py because local testing uses only HTTP).
https://docs.djangoproject.com/en/2.2/ref/settings/#session-cookie-secure

**Comment by Mankro** [comment]
@Gehock would you want to help with this or shall I ask someone else?

**Comment by Mankro** [comment]
@jykesaviaGNH have you noticed problems in the Django session length in Tampere especially in the EXAM studios?

**Comment by Mankro** [comment]
Should we make a separate issue about changing the session backend since it is a bigger operation in production? We have used the default database backend. 

Django has the Memcached backend. There is also `SESSION_ENGINE = django.contrib.sessions.backends.cached_db` that might make more sense for us. This requires further investigation.

**Comment by jykesaviaGNH** [comment]
> @jykesaviaGNH have you noticed problems in the Django session length in Tampere especially in the EXAM studios?

We are using memcached for sessions and I am not aware of any problems with it in EXAM.

**Comment by Mankro** [comment]
There is also the browser cookie session backend that could make sense in the EXAM environment. 

From @ttsirkia 

> if possible, exam sessions could be session-based in cookie instead of expiration time
> or is it a problem if the browser crashes etc.?

Browser crash shouldn't be a problem since A+ does not store exercise submissions in the session. The session only contains the authenticated user.

**Comment by ttsirkia** [comment]
I actually meant this

> SESSION_EXPIRE_AT_BROWSER_CLOSE set to True in local_settings.py

which is already here. So that browser deletes the session from its storage when the browser is closed.

**Comment by raphendyr** [comment]
I would also like to mention that if the EXAM doesn't clear the desktop and browser files, then there is high chance that the same problem will appear with other services too. I think that this kind of use should _always_ have a clean desktop environment and not leave any files from previous student.

Of course, it would make sense to clear over 4 hour old sessions in that system too (e.g. DB query or management script), so that the cookie wouldn't work if it's copied before the environment is deleted.

**Comment by Mankro** [comment]
> I would also like to mention that if the EXAM doesn't clear the desktop and browser files, then there is high chance that the same problem will appear with other services too. I think that this kind of use should _always_ have a clean desktop environment and not leave any files from previous student.
> 
> Of course, it would make sense to clear over 4 hour old sessions in that system too (e.g. DB query or management script), so that the cookie wouldn't work if it's copied before the environment is deleted.

Yes. The issue we had in the EXAM studio is very strange. The classroom computers reset the Windows profile when the student logs out from Windows. (I don't know if some student could have forgotten to log out from Windows after the exam. I am under the impression that these computers use the same Windows account for all users, that is to say, you don't use any personal account to log into Windows.) The browser cookies are stored in the Windows profile and so are local files, thus cookies and local files are deleted when you log out from Windows, or when the computer crashes during the exam. 

A+ was the only system that caused these login issues. The exam.aalto.fi web system did not have this problem. Perhaps exam.aalto.fi always used browser-length sessions, but A+ did not at first. Therefore, the A+ session would remain even after closing the browser. If the student closes the browser after the exam but does not log out from Windows, then that would be the reason why the next student could log into A+ with someone else's account, but not into exam.aalto.fi.

**Comment by Mankro** [comment]
# Summary of settings for normal A+ using Memcached (not EXAM classroom)

Our default settings.py has not defined the session backend in the past. Thus, we have used the default database backend (`SESSIONS_BACKEND`).

* `MIDDLEWARE` in settings.py already contains `'django.contrib.sessions.middleware.SessionMiddleware'`
* `CACHES` must use the Memcached backend.
* `SESSION_ENGINE = "django.contrib.sessions.backends.cache"`
* if we lose sessions too quickly when the cache fills ups and drops data, then we can switch to `SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"`
* `cached_db` requires `'django.contrib.sessions'` in `INSTALLED_APPS` so that the database table can be installed.
* `SESSION_COOKIE_SECURE = True` shall be set as the default in settings.py

# EXAM classroom A+ 
Only one key difference: `SESSION_EXPIRE_AT_BROWSER_CLOSE = True`
