### ISSUE TITLE
HTML Plugin admin interface does not show relevant information

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#769]
Some times we have to copy plugins from previous course instances to the current instance. However, it is difficult to know which plugin belongs to the course we want.

**Current view**
![image](https://user-images.githubusercontent.com/10437475/105320693-25795a80-5bcf-11eb-974a-0bc3fa5ae45c.png)

**Proposed view**
![image](https://user-images.githubusercontent.com/10437475/105320818-5194db80-5bcf-11eb-81b9-73d869a12e26.png)

**Comment by Mankro** [comment]
Adding new columns to the list view in Django admin should be very easy. There should be a simple API for defining them.

https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display
