### ISSUE TITLE
The participants view needs a search functionality to filter the list of participants

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#770]
The current view that shows the list of participants does not provide a search function, and it makes it really difficult to find a student. Especially when there are hundreds of students.

**Current View**
![image](https://user-images.githubusercontent.com/10437475/105322066-fbc13300-5bd0-11eb-8b82-34652ff598a6.png)

**Comment by Mankro** [comment]
The participants page is also too slow: https://github.com/apluslms/a-plus/issues/450

**Comment by Mankro** [comment]
Currently, you can use the browser's built-in search (Ctrl+F) in the participants page. However, it can only match values in one column, thus you should write the student's student ID or the last name in the search.

**Comment by raphendyr** [comment]
My plan was to complete the newest iteration on point page and then use that code for this page too. In sort, the points page is supposed to have cached JS code that downloads list of students or updates cached list and then pulls more data. Same code would work here and in any other place where A+ requires student info.

**Comment by skulonen** [comment]
This would be fixed by PR #939.

**Comment by raphendyr** [comment]
> This would be fixed by PR #939.

If you add "Fixes #770" to the PR, then github will close this issue for you.

**Comment by Mankro** [comment]
#939 has been merged, thus I closed this issue.
