### ISSUE TITLE
Creating and installing new courses requires too much manual work from admins

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#774]
The course creation and installation process must be made easier. Ideally, (authenticated) teachers could create new courses themselves without contacting the A+ support at all.

Currently, teachers send email when they need new courses. The admin must do the following:

* For completely new courses, the A+ Course must be created in the admin UI. The Course model defines the teachers of the course (editing privileges). Currently, teachers can not modify the teachers of the course, only admins can. https://github.com/apluslms/a-plus/pull/738
* New A+ CourseInstance is created in the admin UI. Teachers could clone new instances in the A+ edit course section, but the cloning feature has issues at the moment (#754, #755). (CourseInstance defines the assistants of the course, but teachers can modify themselves.)
* The course instance (course git repo with the right branch) is installed in the MOOC-Grader server. MOOC-Grader has the gitmanager web interface for that. The grader gitmanager interface currently uses IP address whitelisting for the access control. Many teachers would have difficulties with reaching the web interface themselves when it requires very specific proxies to bypass the firewall. The course key for the grader is defined manually and it must be unique because it is also the directory name for the git repo in the grader server's file system. We have tried to name new course keys in a systematic way since the keys are hard to keep track of with a large number of courses.
* The grader uses SSH keys to access the course repos in GitLab version.aalto.fi. Currently, the grader has only one SSH key for the whole system. Course-specific SSH keys could be easier for the teacher since the SSH key must have read access to the course repo in version.aalto.fi. If the teacher does not use the EDIT team's group in version.aalto.fi, the teacher would need to manage SSH keys in version.aalto.fi himself/herself.
* The grader course git hook must be added to the course repo in version.aalto.fi. Any git repo owner could add the hook. The hook URL depends on the grader server URL and the grader course key (directory name).
* If the git repo is new, ensure that the teacher has the GitLab Maintainer role in the course repo.
* The course is imported to the A+ course instance in the A+ edit course section. The teacher could also do this himself/herself once they know the import URL. The import URL depends on the grader server URL and the grader course key (directory name).
* Send the URL of the A+ course instance to the teacher.

The old unfinished projects https://github.com/apluslms/shepherd and https://github.com/apluslms/roman were supposed to solve these problems amongst other things, but they are not progressing since all the developers have left.

**Comment by raphendyr** [comment]
> The old unfinished projects https://github.com/apluslms/shepherd and https://github.com/apluslms/roman were supposed to solve these problems amongst other things, but they are not progressing since all the developers have left.

:cry:

**Comment by Mankro** [comment]
Pull request #1009 closed this issue. The original issue description contains several items and not all of them are part of #1009. However, many details have changed since the original creation of this issue and this issue is outdated. There are some items that are harder to automate, such as automatically adding webhooks in GitLab projects since it is a service out of our control.

#1009 particularly eases the creation of new course instances on existing courses.
