### ISSUE TITLE
Add organization information to user profiles and re-design determination of internal/external users

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#788]
As a preparatory step towards Haka authentication support, add organization information to UserProfile. Use this information in determining whether user is internal or external, instead of the current logic that is based on existence of student number. At this point the user-visible behavior of the system should not change (yet).

The steps to implement this could be as follows:

- Add organization field to UserInfo
- Add local_organization attribute to system settings (local_settings.py?) to indicate the home organization of current deployment (e.g., "aalto.fi" or "tuni.fi")
- modify the logic for UserInfo.is_external such that it compares the system-wide local_organization to user organization
- implement the method for updating the organization information for old user accounts. For example, on login, check whether organization is set yet, and if not, use the old legacy logic based on student number existence to update the organization field for Aalto users as needed.

After this, Haka login could be enabled. Non-Aalto Haka users would show as external users, which is compatible with the current visibility behavior. As a separate later step, a more refined way for presenting different organizations in student listings and respective visibility rules could be designed and implemented.

**Comment by raphendyr** [comment]
Might be related to #505
