### ISSUE TITLE
Clarify submission score.

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#80]
Move or copy submission score from sidebar to Feedback block.
Feedback block contains non scaled score of submission but not scaled (eq. there is 2/4 but not 50/100).

Another good place might be draw blue line on top of exercise points to visualize submission score. This is bad as exercise block is for exercise and not supposed to be mixed with submission.

**Comment by teemulehtinen** [comment]
Currently the feedback block is reserved for the external grader output. Exercise column score is also prone to misunderstandings as it shows the best result for the exercise.

**Comment by raphendyr** [comment]
We expect careful implementation for the assesment tool to ensure that it renders scaled points in the feedback section. If for any reason, the assessment tool reports points in different scale, than configured in A+, then A+ scales those of course.

It would be possible to indicate the scaling better on the A+ side, but it's small enough issue to be left out for now. Something to look when bigger work is done for the student user experience.
