### ISSUE TITLE
Improvements to evaluation user interface

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#831]
- When student has multiple attempts for a task, the maximum achieved points is considered in the final evaluation. This makes it difficult to manually adjust points downwards. There should be an option to always consider the last attempt in final evaluation. The fact that only final submission is evaluated should be indicated to student clearly in the user interface. (e.g.: "This submission will be evaluated)
- The UI should be modified so that students submission is visible as a separate column with the feedback form. Currently it is shown as pop-up window, which prevents editing the comment. Additionally, the UI is currently very confusing with a lot of debug data, and should be cleaned up
- When viewing all submissions to task, there should be option to view only the last submission for each student (when the task is configured as evaluate-last-submission), instead of all submissions

**Comment by skulonen** [comment]
It already is possible for teachers to modify the points of a submission, and provide a comment in the "assistant feedback" field. Do we need a private comment field that is not visible to students, like the "assistant feedback" field is?

The change history still needs to be implemented.

**Comment by PasiSa** [comment]
After today's demo meeting I edited (or rather re-wrote) the issue description, after better understanding the problem points
