### ISSUE TITLE
separate shibboleth and haka logins?

### ISSUE THREAD

**Issue by jykesaviaGNH** [apluslms/a-plus#833]
https://github.com/apluslms/a-plus/blob/6d6baff429ae543f976e3f292bdf6535541bc475/userprofile/templates/userprofile/login.html#L22

If shibboleth login is enabled, haka-login is also included.  Could these be separate items?  A 'haka_login' flag in settings?

**Comment by PasiSa** [comment]
Ella's earlier commit has fixed this issue.
