### ISSUE TITLE
AssertionError  database connection isn't set to UTC

### ISSUE THREAD

**Issue by jykesaviaGNH** [apluslms/a-plus#836]
https://stackoverflow.com/a/68025007
Got hit by this in Debian (bullseye-slim Docker image). It installs psycopg2  version 2.9.1 from https://github.com/apluslms/a-plus/blob/6d6baff429ae543f976e3f292bdf6535541bc475/requirements_prod.txt#L6
and that creates the "database connection isn't set to UTC" error.

Using `psycopg2 >= 2.8.6, <2.9` solves it.
This should be used until A+ upgrades to Django >3.0

**Comment by Mankro** [comment]
A+ v1.10 was actually upgraded to Django v3.2 LTS. That is only a-plus frontend, mooc-grader is still waiting. MOOC-Grader was upgraded to Django v2.2 LTS in the A+ version 1.9 and the Django v3.2 upgrade should be done before April 2022 due to Django v2.2 end-of-life.

**Comment by annirytkonen** [comment]
can be closed
