### ISSUE TITLE
Automatic saving for exercises

### ISSUE THREAD

**Issue by skulonen** [apluslms/a-plus#837]
For exercises that are evaluated manually (see #830, #831), there should be an option to have A+ save the student's progress automatically as they type, instead of with the "submit" button. In practice, this would mean that there is only one submission that is constantly updated, instead of multiple separate submissions. The concept of having a limited number of separate submissions is not actually very useful in manually evaluated exercises, since the student gains no additional information between the submissions via automatic feedback.

This feature is needed particularly in exams, but should be available also otherwise.

**Comment by skulonen** [comment]
Normally, the grader is called immediately when the user makes a submission. In the case of automatically saved exercises, we probably shouldn't call the grader on each save because that would put unnecessary load on the grader. The grader should probably be called A) after a delay, e.g. after it's been 5 mins since the last save, or B) manually by the human grader.

**Comment by raphendyr** [comment]
FYI the old issue #491
