### ISSUE TITLE
Add teachers and assistants to courses API

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#861]
The courses API does not contain information about teachers and assistants for a course. This information might be useful (at least) for IntelliJ plugin assistant mode UI, and Radar access control, and therefore could be added to the API.

**Comment by Mankro** [comment]
Can we include teachers in the API for all users since that includes personal data? Should we reveal the teachers' names in the API only if the client is a teacher too, i.e., students would not see them? Unauthenticated users should not see personal data.
