### ISSUE TITLE
Add a confirmation to the unenrolment of students in the A+ participants page

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#862]
From a teacher:

In the students list, it is dangerously easy for a teacher to misclick 
on a student and remove their enrollment, perhaps even without noticing 
they did that. There isn’t any “are you sure?” dialog either.
I’m not sure what the precise consequences of unenrolling a student are, 
but this is undesirable in any case.

I didn’t dare even to try out the ban buttons.

I worry that I (or my fellow teachers/head TAs) might unenroll and/or 
ban a bunch of students by accident, especially on mobile.

**Comment by skulonen** [comment]
> I’m not sure what the precise consequences of unenrolling a student are, but this is undesirable in any case.

The only consequence is that their enrollment status is changed to removed/banned. Nothing is actually removed, so if the student is re-enrolled, all of their submissions, points, etc are still there.

Nevertheless, there should probably be a confirmation dialog and the UI should explain the consequences of each action, so teachers wouldn't have to fear the buttons.

**Comment by Mankro** [comment]
The severe consequence is that the student is not able to enroll back into the course if the enrollment has closed. The teacher also discovered that students can run out of submission attempts in the enrollment questionnaire, which then prevents them from enrolling again.

**Comment by skulonen** [comment]
Yes, that's true. In my previous comment I was thinking about a case where the teacher would notice their mistake and immediately re-enroll the student back into the course.
