### ISSUE TITLE
Enrollment questionnaire should not have any max submissions limit for an unenrolled user

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#864]
Students may run out of submission attempts in enrollment questionnaires when the questionnaire has a low max submissions limit, such as only one. In the first time, this is not a problem. If the student is unenrolled, then it is a problem because the student is not able submit to the questionnaire and that prevents enrolling back into the course. This is particularly problematic when the student was unenrolled by accident; they really want to get back in then. The teacher may manually enroll the student, but that requires the teacher to take action.

However, if the student is enrolled, she should not have unlimited submission attempts in the enrollment questionnaire (in order to avoid spam). Enrolled students might want to submit the questionnaire if they were enrolled without ever submitting the questionnaire. Multiple submissions are usually not needed, though perhaps there could be a use case for changing some incorrect answer in the previous submission.

**Comment by Mankro** [comment]
Method `one_has_submissions` could ignore the exercise.max_submissions if exercise.status is ENROLLMENT or ENROLLMENT_EXT and there is only one submitter and the submitter is not enrolled in the course (may have an enrollment with the status REMOVED or no enrollment object at all).

https://github.com/apluslms/a-plus/blob/d94dff0da990924b5e4579d33673b6b95e67d0a9/exercise/exercise_models.py#L640

**Comment by skulonen** [comment]
There's another problem here:
1. student forms a group and activates that group from the navbar menu
2. teacher removes the student from the course by accident
3. student attempts to re-enroll
4. enrollment exercise can't be submitted because the student has activated a group
5. student can't deactivate the group because the navbar menu is not visible

Seems like we also need to ignore the user's active group if the enrollment is not active.

**Comment by Mankro** [comment]
> There's another problem here:
> 
>     1. student forms a group and activates that group from the navbar menu
> 
>     2. teacher removes the student from the course by accident
> 
>     3. student attempts to re-enroll
> 
>     4. enrollment exercise can't be submitted because the student has activated a group
> 
>     5. student can't deactivate the group because the navbar menu is not visible
> 
> 
> Seems like we also need to ignore the user's active group if the enrollment is not active.

Would it be easier to remove the group selection from the enrollment when the enrollment is removed (status set to REMOVED or BANNED)?

**Comment by skulonen** [comment]
> Would it be easier to remove the group selection from the enrollment when the enrollment is removed (status set to REMOVED or BANNED)?

No, it's easy to check for this situation in `_check_submission_allowed`.

But there's yet another problem: submissions that go past the submission limit are marked as UNOFFICIAL by A+. However, only submissions with status READY can enroll the student, as seen here:

https://github.com/apluslms/a-plus/blob/d94dff0da990924b5e4579d33673b6b95e67d0a9/exercise/views.py#L168-L173

Should we accept both READY or UNOFFICIAL submissions here? Or should we instead never mark enrollment exercise submissions as UNOFFICIAL?

**Comment by Mankro** [comment]
UNOFFICIAL submissions shouldn't be possible if the exercise category has not enabled the `accept_unofficial_submits` field. Therefore, we should use the READY status in the submission and ensure that unenrolled users may submit normally even after exceeding the exercise.max_submissions limit. In my previous post, I was suggesting that the method `one_has_submissions` could be the right place for that.

In addition, submission.set_points must skip setting the UNOFFICIAL status. The exercise.no_submissions_left could be changed to return zero if the exercise has the status(es) enrollment(_ext) and the student does not have an active enrollment. Similar to `one_has_submissions`.

https://github.com/apluslms/a-plus/blob/4271e485c768172a5317582d8ba3c73b04e006e4/exercise/exercise_models.py#L660
https://github.com/apluslms/a-plus/blob/4271e485c768172a5317582d8ba3c73b04e006e4/exercise/submission_models.py#L321
