### ISSUE TITLE
Improve deadline deviation UI for adjusting multiple students and/or exercises at a time

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#896]
Deadline deviations view is unusable because each deviation is shown separately for each task and each student, which creates a large number of individual deviation entries on large courses. For example, a group of high school students may need to be given the same deviation for an entire exercise round. Some proposed ideas from @jsorva:

- Allow showing/adjusting deviations for entire exercise round, instead of each exercise separately
- Grant deviations for groups of students at a time. One idea could be to leverage user tags for this

Some related user interface tweaks:

- Deviation list should also show the chapter in addition to task name (that may be repeated in different chapters/modules)
- Could show the approver of deviation

**Comment by Mankro** [comment]
Related to:

Changes the teacher's deviation UI:
* https://github.com/apluslms/a-plus/pull/401

Student's UI for seeing the extended deadline:
* https://github.com/apluslms/a-plus/pull/398
* https://github.com/apluslms/a-plus/issues/529 
* https://github.com/apluslms/a-plus/issues/624

The recent delayed feedback feature changed the points cache and it now already contains some personal deviations:
https://github.com/apluslms/a-plus/issues/882#issuecomment-947856430

**Comment by PasiSa** [comment]
[Issue 693](https://jira.aalto.fi/browse/EDIT-693) in EDIT Jira

**Comment by Mankro** [comment]
Easy copy-pasting of the user selection:
https://github.com/apluslms/a-plus/issues/903#issuecomment-963919912
