### ISSUE TITLE
Support dark mode in A+ UI

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#898]
Many of the O1 students have requested this.

**Comment by Mankro** [comment]
Since courses can add their own CSS styles to the course pages in A+, any base theme (light/dark) in A+ might break in some courses. Though, that is not really our problem since the course staff is responsible for their own CSS.

A dark mode not only looks nicer (for some people at least), but it can also reduce eye strain since the screen has less blue light.

**Comment by annirytkonen** [comment]
additional wish from the A+ feedback form

**Comment by annirytkonen** [comment]
yet another vote from the A+ feedback form!

**Comment by annirytkonen** [comment]
articles on the topic:
* https://medium.com/@h_locke/why-dark-mode-causes-more-accessibility-issues-than-it-solves-d2f8359bb46a
* https://blogs.perficient.com/2022/03/04/dark-mode-and-digital-accessibility-who-it-helps-and-without-it-who-it-may-hinder/
* dark mode: a preference of minority, not usability or accessibility: https://uxdesign.cc/dark-matters-342ff2c7cc

Instructions:
* https://webaim.org/articles/contrast/ 
* https://mn.gov/mnit/media/blog/?id=38-469250
* https://www.saavutettavasti.fi/verkkosisaltojen-saavutettavuus/linkkeja-ja-tyokaluja/ (in Finnish)

**Comment by Mankro** [comment]
A+ still uses the outdated Bootstrap version 3 CSS/JS framework. If the frontend styles are changed a lot, it could make sense to first upgrade Bootstrap or change the CSS framework. Upgrade issue: #584

**Comment by annirytkonen** [comment]
based on discussion: this is a wish from students - so, we could suggest this to some student course projects. Currently we haven't the resources for focusing on this. But, the issue remains open, and if it receives more votes, we'll return to the need.

**Comment by mikaelGusse** [comment]
This has been discussed again in our weekly meeting and it was determined again that this is not going to be implemented into A+. The difficulty with implementing it is that the materials are created by teachers and converting these images neatly into Dark Mode versions would be challenging. For now we suggest using the Dark Reader browser extension which has been proven to work well with A+ ([https://darkreader.org/](https://darkreader.org/)).

**Comment by ihalaij1** [comment]
An experimental dark mode is now available since the Bootstrap 5 upgrade: #1442, #584
