### ISSUE TITLE
Modification of existing deadline deviation

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#902]
It should be possible to modify existing deadline deviation. Currently an earlier deviation needs to be removed and new one needs to be added separately, which is tedious to use.

**Comment by PasiSa** [comment]
[Issue 696](https://jira.aalto.fi/browse/EDIT-696) in EDIT Jira

**Comment by Mankro** [comment]
In the old PR https://github.com/apluslms/a-plus/pull/401, the "add deadline deviation" form can override existing deviations automatically if they already exist. That idea might still be useful. However, it also makes sense to add a new simple edit form for modifying a single existing deviation.

**Comment by Mankro** [comment]
Pull request #958 added the override feature to adding new deviations. There is no edit form for a single existing deviations, but the teachers have said it is not important.
