### ISSUE TITLE
Allow giving deadline deviation to multiple users at a time

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#903]
In some cases a group of students needs to be given the same deadline deviation. Currently each user needs to be added separately, which takes much time and effort. It should be possible to provide a list of users in "submitters" field somehow, for example, as a comma-separated list.

Same field type (UserSearchSelectField) is used also in other places in UI (e.g., when setting teaching assistants). Possibility of enabling multiple users at a time might be useful also in these places.

**Comment by Mankro** [comment]
This issue description was a bit wrong. The "add deadline deviation" form already allows selecting multiple users, but it is not possible to copy-paste the selection to another form. Easy copy-pasting would be useful.

@PasiSa should we actually re-open this issue?

See also #896.

**Comment by PasiSa** [comment]
I had closed this, because I had forgot that essentially same issue was there already earlier
